In [1]:
import os
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
print(f'Latest run date: {dt.datetime.today()}')

Latest run date: 2025-02-18 21:39:44.606969

#### Functions

#### Constants

In [3]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')

str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

str_dirname_output = './output'

Project: 20241112-simple-model-test
Task: get_aa_dfs

#### Output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Indirect

In [5]:
str_model = '09_60_in_720'

# get model features
list_cols = [
    'feature',
]
str_filename = 'df_feat_imp.csv'
str_local_path = f'../{str_model}/02_model/output/{str_filename}'
df = pd.read_csv(str_local_path, usecols=list_cols)
df['feature'] = df['feature'].apply(
    lambda x: x.split('_binned')[0],
)

# get the AA dict
str_filename = 'df_aa.csv'
str_local_path = f'../{str_model}/06_parser/input/{str_filename}'
df_tmp = pd.read_csv(str_local_path)

# join
df = pd.merge(
    left=df,
    right=df_tmp,
    on='feature',
    how='left',
)

# replace
df['model'] = 'gen-xiii'

# drop
df.drop('Change Reason/Comment', axis=1, inplace=True)

# save
str_filename = 'df_aa_indirect.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

,feature,reason,model,description
0,fltgrossmonthly__income_sum,Insufficient income,gen-xiii,NaN
1,miles_odometer__app,Value or type of collateral not sufficient,gen-xiii,Vehicle milegae
2,au20s__tu,"Insufficient credit file, Length of Credit",gen-xiii,Months since oldest auto trade opened
3,rtl_trd__tu,"Insufficient credit file, Length of Credit",gen-xiii,Number of retail trades
4,ENG-loan_to_value,Value or type of collateral not sufficient,gen-xiii,Loan to value
5,rev322__tu,Excessive Account Balances,gen-xiii,Min Total Open-to-Buy for Revolving accounts o...
6,balmag01__tu,Excessive Account Balances,gen-xiii,Non-mortgage balance magnitude algorithm over ...
7,g232s__tu,Excessive inquiries,gen-xiii,Number of inquiries (includes duplicates)
8,g002s__tu,Delinquent credit obligations,gen-xiii,Number of 60 days past due ratings in past 12 ...
9,linkt003__tu,Length of residence,gen-xiii,Number of non-military non-corroborated addres...
10,inquirybanking12month__ln,Excessive inquiries,gen-xiii,Indicates subject has one or more LexisNexis b...
11,all235__tu,Excessive Account Balances,gen-xiii,Aggregate Excess Payment for All accounts over...
12,cv15__tu,Excessive inquiries,gen-xiii,Number of deduped auto inquiries
13,derogseverityindex__ln,Derogatory public record,gen-xiii,Index indicating severity of derogatory record...
14,cv13__tu,Delinquent credit obligations,gen-xiii,Percentage of trades ever delinquent
15,ENG-wtd_avg,Derogatory Payments on Accounts,gen-xiii,Weighted average of payment history string of ...
16,subjectabilityindex__ln,Derogatory public record,gen-xiii,Modeled risk index indicating the subject's ab...
17,g407s__tu,Excessive inquiries,gen-xiii,Number of deduped finance inquiries
18,ENG-franchise,Dealer application source,gen-xiii,Tag to indicate franchise dealer
19,phoneinputproblems__ln,Unable to verify working phone number,gen-xiii,Indicates problems associated with the input p...
20,at24s__tu,Delinquent credit obligations,gen-xiii,Number of currently open and satisfactory trad...
21,jt20s__tu,Insufficient length of credit history,gen-xiii,Months since oldest joint trade opened
22,rp01s__tu,"Garnishment, or attachment, or foreclosure, or...",gen-xiii,Number of repossession trades
23,sourcenonderogcount12month__ln,Delinquent credit obligations,gen-xiii,Total non-derogatory source types on file for ...
24,in21s__tu,Insufficient credit history,gen-xiii,Months since most recent installment trade opened
25,ENG-bk,Excessive Number of Accounts,gen-xiii,Flag for Open BK
26,bc97a__tu,Excessive Account Balances,gen-xiii,Total open to buy of open credit cards verifie...
27,addrprevioustimenewest__ln,Length of residence,gen-xiii,Time (in months) since the subject was most re...
28,trv01__tu,High revolving credit balances,gen-xiii,Number of months since overlimit on a bankcard
29,s068b__tu,Delinquent credit obligations,gen-xiii,Number of non-medical third party collections
30,in34s__tu,Excessive Account Balances,gen-xiii,Utilization for open installment trades verifi...
31,addronfilecount__ln,Length of residence,gen-xiii,Total number of addresses found on file in sub...
32,linka053__tu,Excessive inquiries,gen-xiii,Number of days since the first (oldest) checki...
33,fi101s__tu,Excessive Account Balances,gen-xiii,Total balance of all finance installment trade...
34,fi36s__tu,Delinquent credit obligations,gen-xiii,Months since most recent finance installment d...
35,linkf098__tu,Delinquent credit obligations,gen-xiii,Number of satisfactory trades
36,linka006__tu,Excessive Inquiries,gen-xiii,Number of total inquiries in the last 3 years....
37,fi25s__tu,Delinquent credit obligations,gen-xiii,Number of currently open and satisfactory fina...
38,addrinputsubjectcount__ln,Length of residence,gen-xiii,Total number of unique subjects on file curren...
39,linka025__tu,Excessive inquiries,gen-xiii,Number of other inquiries in the last 3 years....
40,g251c__tu,Delinquent credit obligations,gen-xiii,Number of 60 days past due or worse items in t...
41,inquiryshortterm12month__ln,Excessive inquiries,gen-xiii,Indicates subject has one or more LexisNexis p...
42,g095s__tu,Derogatory public record,gen-xiii,Months since most recent public record
43,s209a__tu,Delinquent credit obligations,gen-xiii,Months since most recent non-medical third par...
44,inquirynonshortterm12month__ln,Excessive inquiries,gen-xiii,Indicates subject has one or more LexisNexis c...

#### Direct

In [6]:
str_model = '13_60_in_720_dl'

# get model features
list_cols = [
    'feature',
]
str_filename = 'df_feat_imp.csv'
str_local_path = f'../{str_model}/02_model/output/{str_filename}'
df = pd.read_csv(str_local_path, usecols=list_cols)
df['feature'] = df['feature'].apply(
    lambda x: x.split('_binned')[0],
)

# get the AA dict
str_filename = 'df_aa.csv'
str_local_path = f'../{str_model}/06_parser/input/{str_filename}'
df_tmp = pd.read_csv(str_local_path)

# join
df = pd.merge(
    left=df,
    right=df_tmp,
    on='feature',
    how='left',
)

# replace
df['model'] = 'dlv2'

# drop
df.drop('Change Reason/Comment', axis=1, inplace=True)

# save
str_filename = 'df_aa_direct.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

,feature,reason,model,description
0,linkt001__tu,Length of residence,dlv2,Number of non-military addresses in last 7 years
1,au20s__tu,"Insufficient credit file, Length of Credit",dlv2,Months since oldest auto trade opened
2,rtl_trd__tu,"Insufficient credit file, Length of Credit",dlv2,Number of retail trades
3,rev326__tu,Excessive Account Balances,dlv2,Average Total Open-to-Buy for Revolving accoun...
4,br109s__tu,Delinquent credit obligations,dlv2,Number of bank revolving trades with past due ...
5,miles_odometer__app,Value or type of collateral not sufficient,dlv2,Vehicle milegae
6,fltgrossmonthly__income_sum,Insufficient income,dlv2,NaN
7,balmag01__tu,Excessive Account Balances,dlv2,Non-mortgage balance magnitude algorithm over ...
8,ENG-loan_to_value,Value or type of collateral not sufficient,dlv2,Loan to value
9,int_n_months_open__tu_pmthx,Insufficient credit history,dlv2,Months on file of most recent open auto
10,rp01s__tu,"Garnishment, or attachment, or foreclosure, or...",dlv2,Number of repossession trades
11,jt20s__tu,Insufficient length of credit history,dlv2,Months since oldest joint trade opened
12,trv10__tu,Excessive Account Balances,dlv2,Number of months non-mortgage balance decrease...
13,trv13__tu,High revolving credit balances,dlv2,Number of revolving high credit increases YOY
14,cv15__tu,Excessive inquiries,dlv2,Number of deduped auto inquiries
15,linkt003__tu,Length of residence,dlv2,Number of non-military non-corroborated addres...
16,g002s__tu,Delinquent credit obligations,dlv2,Number of 60 days past due ratings in past 12 ...
17,flt_wtd_avg_closed__tu_pmthx,Derogatory Payments on Accounts,dlv2,Weighted average of payment history string of ...
18,co01s__tu,Delinquent credit obligations,dlv2,Number of charged-off trades
19,g407s__tu,Excessive inquiries,dlv2,Number of deduped finance inquiries
20,g232s__tu,Excessive inquiries,dlv2,Number of inquiries (includes duplicates)
21,linkf098__tu,Delinquent credit obligations,dlv2,Number of satisfactory trades
22,st20s__tu,"Insufficient credit file, Length of Credit",dlv2,Months since oldest student loan trade opened
23,per235__tu,Excessive Account Balances,dlv2,Aggregate Excess Payment for Personal Loan acc...
24,linka006__tu,Excessive Inquiries,dlv2,Number of total inquiries in the last 3 years....
25,in30s__tu,Excessive Account Balances,dlv2,Percentage of open installment trades > 50% of...
26,linka003__tu,Excessive Inquiries,dlv2,Number of other inquiries in the last 2 years....
27,fi25s__tu,Delinquent credit obligations,dlv2,Number of currently open and satisfactory fina...
28,in21s__tu,Insufficient credit history,dlv2,Months since most recent installment trade opened
29,fi36s__tu,Delinquent credit obligations,dlv2,Months since most recent finance installment d...
30,aut252__tu,Excessive Account Balances,dlv2,Average Aggregate Excess Payment for Auto acco...
31,s068b__tu,Delinquent credit obligations,dlv2,Number of non-medical third party collections
32,flt_wtd_avg_open__tu_pmthx,Derogatory Payments on Accounts,dlv2,Average of payment history string of most rece...