## Imports

In [1]:
import os
import pandas as pd
import numpy as np

## Constants

In [2]:
str_dirname_output = './output'
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

## Read

In [3]:
str_filename = 'df_ecnl.csv'
df = pd.read_csv(f'./input/df_ecnl.csv')
df.head(10)

,bigAccountId,bigDealerId,week_of_month,application_date,dtmFunded,dtmNonAccrual,intterm,open_bk_type,first_pmt_date,paymentsmade,...,LoanStatus,ChargeOff_Severity,GEN11_ExpectedNetLoss,GEN11_ECNL,GEN12_ExpectedNetLoss,GEN12_ECNL,GEN12_ECNL_mod,DL_ExpectedNetLoss,DL_ECNL,origination_model
0,7622142,2836,4,44:51.2,00:00.0,NaN,72,13.0,00:00.0,2.0,...,A,NaN,2462.247980,0.095872,1898.025622,0.073903,0.051137,NaN,NaN,gen11
1,7794020,939,4,54:06.9,00:00.0,NaN,72,7.0,00:00.0,NaN,...,A,NaN,1203.251490,0.087003,1190.126820,0.086054,0.059545,NaN,NaN,gen11
2,7844199,2947,4,01:16.3,00:00.0,NaN,72,13.0,00:00.0,NaN,...,A,NaN,1621.960426,0.073042,2405.094491,0.108309,0.074945,NaN,NaN,gen11
3,7893285,7480,4,32:15.1,00:00.0,NaN,72,7.0,00:00.0,1.0,...,A,NaN,2026.329035,0.118288,9035.534923,0.527454,0.223498,NaN,NaN,gen11
4,7897599,8308,4,29:15.2,00:00.0,NaN,72,NaN,00:00.0,1.0,...,A,NaN,2632.401450,0.118125,10632.918500,0.477136,0.202176,NaN,NaN,gen11
5,7909310,4250,4,49:24.2,00:00.0,NaN,72,7.0,00:00.0,NaN,...,A,NaN,4535.329257,0.147052,2498.144428,0.080999,0.056047,NaN,NaN,gen12
6,7910522,6845,4,50:07.8,00:00.0,NaN,48,NaN,00:00.0,NaN,...,A,NaN,1646.546137,0.097343,3230.388777,0.190979,0.123076,NaN,NaN,gen11
7,7916574,3171,4,19:19.9,00:00.0,NaN,72,NaN,00:00.0,NaN,...,A,NaN,1291.481648,0.090462,4908.249861,0.343799,0.145678,NaN,NaN,gen11
8,7919227,1727,4,47:33.3,00:00.0,NaN,66,7.0,00:00.0,NaN,...,A,NaN,1572.411456,0.085184,6532.713936,0.353904,0.149959,NaN,NaN,gen11
9,7921215,8116,4,00:03.6,00:00.0,NaN,72,NaN,00:00.0,NaN,...,A,NaN,4513.352839,0.184530,3985.168508,0.162935,0.105003,NaN,NaN,gen12

In [4]:
df_ecnl = df[['bigAccountId', 'AmtFinanced', 'mnyDiscount', 'mnyReserve', 'fltAPRCurrent', 'Tier', 'GEN11_ECNL']]
df_ecnl.head(10)

,bigAccountId,AmtFinanced,mnyDiscount,mnyReserve,fltAPRCurrent,Tier,GEN11_ECNL
0,7622142,25682.66,3278,941.47,0.2500,B,0.095872
1,7794020,13830.00,505,872.42,0.2524,B,0.087003
2,7844199,22205.86,539,1397.59,0.2524,B,0.073042
3,7893285,17130.47,1390,0.00,0.2324,B,0.118288
4,7897599,22284.88,928,726.77,0.2555,B,0.118125
5,7909310,30841.67,1378,84.17,0.2100,A,0.147052
6,7910522,16914.89,500,645.12,0.2424,B,0.097343
7,7916574,14276.51,219,900.14,0.2524,B,0.090462
8,7919227,18459.00,149,368.21,0.2395,B,0.085184
9,7921215,24458.64,928,928.87,0.2995,B,0.184530

In [16]:
# formulas for each tier category to calc theo_rev
# each named var here is the default value, but in the app, each var corresponds to a user-input value
values_A1 = (.0807 + 1.11 * (df['GEN12_ECNL'])/1.5209) * .275 + (1-(.0807 + 1.11 * (df['GEN12_ECNL'])/1.5209)) * .07 + .0564 + (df['GEN12_ECNL'])/2.3) - ((df['GEN12_ECNL']/1.5209) * 0.008)
values_A = (.0807 + 1.11 * (df['GEN12_ECNL'])) * .275 + (1-(.0807 + 1.11 * (df['GEN12_ECNL']))) * .07 + .0603 + ((df['GEN12_ECNL'])*1.5209/2.3)
values_B = (.0807 + 1.11 * (df['GEN12_ECNL'])) * .275 + (1-(.0807 + 1.11 * (df['GEN12_ECNL']))) * .07 + .0639 + ((df['GEN12_ECNL'])*1.633/2.3)
values_C = (.0807 + 1.11 * (df['GEN12_ECNL'])) * .275 + (1-(.0807 + 1.11 * (df['GEN12_ECNL']))) * .07 + .0639 + ((df['GEN12_ECNL'])*1.5209/2.3)
values_D = (.0807 + 1.11 * (df['GEN12_ECNL'])) * .275 + (1-(.0807 + 1.11 * (df['GEN12_ECNL']))) * .07 + .0639 + ((df['GEN12_ECNL'])*1.5209/2.3)

# incorporate dynamic formula to calculate the theo_rev for each tier category
    # originally did not work since i had to distinguish gen11/12 which in that case had to use the numpy below (not fun)
for i in df.Tier:
    if i == 'A1':
        df['GEN11_Theo_Rev'] = values_A1
    elif i == 'A':
        df['GEN11_Theo_Rev'] = values_A
    elif i == 'B':
        df['GEN11_Theo_Rev'] = values_B
    elif i == 'C' or 'D':
        df['GEN11_Theo_Rev'] = values_C

# # THE FOLLOWING IS NOT NEEDED SINCE ONLY GEN12 AS OF 7/12
# # initialize the column with default values
# df['GEN11_Theo_Rev'] = np.nan

# # use np.where to assign values based on conditions
# df['GEN11_Theo_Rev'] = np.where(
#     (df['Tier'] == 'A1') & (df['bigAccountId'] % 5 != 0), values_A1,
#     np.where(
#         (df['Tier'] == 'A') & (df['bigAccountId'] % 5 != 0), values_A,
#         np.where(
#             (df['Tier'] == 'B') & (df['bigAccountId'] % 5 != 0), values_B,
#             np.where(
#                 ((df['Tier'] == 'C') | (df['Tier'] == 'D')) & (df['bigAccountId'] % 5 != 0), values_C, 
#                 df['GEN11_Theo_Rev']
#                    ... add rest ...
#             )
#         )
#     )
# )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [10]:
df['GEN11_Theo_Rev'].head

<bound method NDFrame.head of 0     0.240328
1          NaN
2     0.218924
3          NaN
4     0.261192
5          NaN
6     0.241707
7     0.235256
8     0.230308
9          NaN
10    0.288458
11    0.314879
12    0.277575
13    0.312624
14    0.259980
15    0.251898
16    0.270092
17    0.265422
18    0.250166
19    0.244716
20         NaN
21    0.301605
22    0.294271
23    0.248966
24    0.257474
25    0.228516
26    0.222197
27    0.200766
28    0.231219
29    0.194687
30    0.276336
31    0.291892
32    0.310175
33    0.317030
34    0.307939
35    0.300288
36    0.249386
37    0.245732
38    0.271095
39    0.285851
40    0.272627
41    0.272236
42    0.223133
43    0.276812
44    0.307305
45    0.304525
46    0.236729
47    0.219141
Name: GEN11_Theo_Rev, dtype: float64>

In [11]:
df['Actual_Rev'] = df['OriginalInterestRate'] + ((df['mnyDiscount'] - df['mnyReserve']) / df['AmtFinanced'])/2.3
df['Actual_Rev'].head

<bound method NDFrame.head of 0     0.289555
1     0.240849
2     0.235589
3     0.267679
4     0.259426
5     0.228239
6     0.238670
7     0.231656
8     0.234337
9     0.299485
10    0.288795
11    0.300030
12    0.278764
13    0.309951
14    0.259648
15    0.243933
16    0.272237
17    0.248392
18    0.239278
19    0.247608
20    0.300010
21    0.288996
22    0.295974
23    0.248997
24    0.251196
25    0.228779
26    0.236993
27    0.199738
28    0.236098
29    0.191750
30    0.276115
31    0.306343
32    0.322593
33    0.301951
34    0.305149
35    0.305791
36    0.254139
37    0.241162
38    0.265240
39    0.293767
40    0.278577
41    0.274802
42    0.243414
43    0.274578
44    0.309416
45    0.305701
46    0.237155
47    0.236438
Name: Actual_Rev, dtype: float64>

In [12]:
df['Rev_Diff'] = df['Actual_Rev'] - df['GEN11_Theo_Rev']
df['Rev_Diff'].head

<bound method NDFrame.head of 0     0.049227
1          NaN
2     0.016665
3          NaN
4    -0.001766
5          NaN
6    -0.003038
7    -0.003600
8     0.004029
9          NaN
10    0.000337
11   -0.014849
12    0.001189
13   -0.002673
14   -0.000333
15   -0.007965
16    0.002145
17   -0.017030
18   -0.010888
19    0.002892
20         NaN
21   -0.012609
22    0.001703
23    0.000031
24   -0.006278
25    0.000263
26    0.014796
27   -0.001028
28    0.004879
29   -0.002937
30   -0.000221
31    0.014450
32    0.012418
33   -0.015079
34   -0.002790
35    0.005503
36    0.004753
37   -0.004571
38   -0.005855
39    0.007916
40    0.005950
41    0.002566
42    0.020282
43   -0.002234
44    0.002111
45    0.001176
46    0.000426
47    0.017297
Name: Rev_Diff, dtype: float64>

In [13]:
df = df.sort_values(by=['Rev_Diff'], ascending=True)
df

,bigAccountId,bigDealerId,week_of_month,application_date,dtmFunded,dtmNonAccrual,intterm,open_bk_type,first_pmt_date,paymentsmade,...,GEN11_ECNL,GEN12_ExpectedNetLoss,GEN12_ECNL,GEN12_ECNL_mod,DL_ExpectedNetLoss,DL_ECNL,origination_model,GEN11_Theo_Rev,Actual_Rev,Rev_Diff
17,7935253,2612,4,23:13.7,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.122637,2709.543923,0.078486,0.050580,NaN,NaN,gen11,0.265422,0.248392,-0.017030
33,7947387,7980,4,44:58.4,00:00.0,NaN,66,NaN,00:00.0,NaN,...,0.187426,13270.548020,0.707615,0.299837,NaN,NaN,gen11,0.317030,0.301951,-0.015079
11,7926947,8171,4,10:05.1,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.185006,2492.094279,0.138273,0.095678,NaN,NaN,gen11,0.314879,0.300030,-0.014849
21,7943081,342,4,09:52.1,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.170072,11000.536980,0.374296,0.158600,NaN,NaN,gen11,0.301605,0.288996,-0.012609
18,7935981,3615,4,25:00.5,00:00.0,NaN,72,13.0,00:00.0,NaN,...,0.106365,2749.683191,0.118209,0.081795,NaN,NaN,gen11,0.250166,0.239278,-0.010888
15,7934934,8406,4,23:01.3,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.108212,2975.059175,0.135765,0.093942,NaN,NaN,gen11,0.251898,0.243933,-0.007965
24,7944606,6502,4,23:39.5,00:00.0,NaN,48,NaN,00:00.0,NaN,...,0.114160,16642.345660,0.517747,0.219385,NaN,NaN,gen11,0.257474,0.251196,-0.006278
38,7956801,2687,4,13:28.9,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.128688,3018.478647,0.127215,0.088026,NaN,NaN,gen11,0.271095,0.265240,-0.005855
37,7954554,6641,4,28:02.7,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.101636,8207.749474,0.433302,0.183602,NaN,NaN,gen11,0.245732,0.241162,-0.004571
7,7916574,3171,4,19:19.9,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.090462,4908.249861,0.343799,0.145678,NaN,NaN,gen11,0.235256,0.231656,-0.003600
6,7910522,6845,4,50:07.8,00:00.0,NaN,48,NaN,00:00.0,NaN,...,0.097343,3230.388777,0.190979,0.123076,NaN,NaN,gen11,0.241707,0.238670,-0.003038
29,7946662,2254,4,57:21.1,00:00.0,NaN,72,13.0,00:00.0,NaN,...,0.053829,1432.270582,0.052582,0.033886,NaN,NaN,gen11,0.194687,0.191750,-0.002937
34,7950984,7348,4,54:14.1,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.177198,11880.938570,0.507568,0.215071,NaN,NaN,gen11,0.307939,0.305149,-0.002790
13,7927574,5702,4,12:54.5,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.182469,13548.084910,0.677085,0.286901,NaN,NaN,gen11,0.312624,0.309951,-0.002673
43,7959069,5375,4,28:57.4,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.142177,6412.523063,0.330958,0.140236,NaN,NaN,gen11,0.276812,0.274578,-0.002234
4,7897599,8308,4,29:15.2,00:00.0,NaN,72,NaN,00:00.0,1.0,...,0.118125,10632.918500,0.477136,0.202176,NaN,NaN,gen11,0.261192,0.259426,-0.001766
27,7946301,2555,4,14:42.0,00:00.0,NaN,72,13.0,00:00.0,NaN,...,0.060668,2001.659862,0.075274,0.052086,NaN,NaN,gen11,0.200766,0.199738,-0.001028
14,7931441,5900,4,59:48.7,00:00.0,NaN,66,7.0,00:00.0,NaN,...,0.116833,3400.108089,0.173803,0.112007,NaN,NaN,gen11,0.259980,0.259648,-0.000333
30,7946939,4256,4,57:06.3,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.134278,2791.892240,0.166199,0.107107,NaN,NaN,gen11,0.276336,0.276115,-0.000221
23,7943784,3439,4,41:23.3,00:00.0,NaN,66,7.0,00:00.0,NaN,...,0.105085,6463.919254,0.203996,0.131465,NaN,NaN,gen11,0.248966,0.248997,0.000031
25,7945394,3439,4,16:30.1,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.083273,9826.591230,0.321117,0.136067,NaN,NaN,gen11,0.228516,0.228779,0.000263
10,7924777,6212,4,14:03.2,00:00.0,NaN,60,NaN,00:00.0,NaN,...,0.155280,10660.402030,0.637471,0.270115,NaN,NaN,gen11,0.288458,0.288795,0.000337
46,7959873,1284,4,41:55.0,00:00.0,NaN,60,NaN,00:00.0,NaN,...,0.092033,1447.026186,0.084618,0.058551,NaN,NaN,gen11,0.236729,0.237155,0.000426
45,7959588,6642,4,46:58.2,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.173357,13437.172170,0.533087,0.225884,NaN,NaN,gen11,0.304525,0.305701,0.001176
12,7927446,6523,4,37:40.0,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.143035,21922.828200,0.826884,0.350375,NaN,NaN,gen11,0.277575,0.278764,0.001189
22,7943336,6502,4,30:31.0,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.161820,12992.948290,0.616113,0.261065,NaN,NaN,gen11,0.294271,0.295974,0.001703
44,7959404,2814,4,34:28.7,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.176485,9626.790415,0.433237,0.183575,NaN,NaN,gen11,0.307305,0.309416,0.002111
16,7935144,4229,4,07:19.1,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.127618,8321.969541,0.379147,0.160656,NaN,NaN,gen11,0.270092,0.272237,0.002145
41,7957981,6642,4,17:24.6,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.129905,2281.333431,0.128326,0.088795,NaN,NaN,gen11,0.272236,0.274802,0.002566
19,7938514,3287,4,26:51.5,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.100552,8253.871212,0.346800,0.146949,NaN,NaN,gen11,0.244716,0.247608,0.002892
8,7919227,1727,4,47:33.3,00:00.0,NaN,66,7.0,00:00.0,NaN,...,0.085184,6532.713936,0.353904,0.149959,NaN,NaN,gen11,0.230308,0.234337,0.004029
36,7951973,6414,4,13:28.4,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.105533,3961.862228,0.139272,0.096369,NaN,NaN,gen11,0.249386,0.254139,0.004753
28,7946338,2649,4,28:55.0,00:00.0,NaN,60,NaN,00:00.0,NaN,...,0.086156,3109.762652,0.177508,0.114395,NaN,NaN,gen11,0.231219,0.236098,0.004879
35,7951321,7207,4,52:10.0,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.168590,7869.413675,0.493542,0.209128,NaN,NaN,gen11,0.300288,0.305791,0.005503
40,7957663,6212,4,53:20.6,00:00.0,NaN,66,NaN,00:00.0,NaN,...,0.130322,1636.087715,0.096381,0.066691,NaN,NaN,gen11,0.272627,0.278577,0.005950
39,7957186,5161,4,57:40.9,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.152347,7181.689951,0.339887,0.144020,NaN,NaN,gen11,0.285851,0.293767,0.007916
32,7947291,3422,4,23:43.4,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.179714,9182.648800,0.540800,0.229152,NaN,NaN,gen11,0.310175,0.322593,0.012418
31,7947088,6461,4,32:52.6,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.159144,6663.668990,0.323784,0.137197,NaN,NaN,gen11,0.291892,0.306343,0.014450
26,7946204,6642,4,38:37.6,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.076533,9819.379762,0.368067,0.155960,NaN,NaN,gen11,0.222197,0.236993,0.014796
2,7844199,2947,4,01:16.3,00:00.0,NaN,72,13.0,00:00.0,NaN,...,0.073042,2405.094491,0.108309,0.074945,NaN,NaN,gen11,0.218924,0.235589,0.016665
47,7960819,7418,4,41:24.8,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.073273,1920.439640,0.119960,0.083006,NaN,NaN,gen11,0.219141,0.236438,0.017297
42,7959059,5486,4,26:05.7,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.077531,2803.945032,0.158201,0.101952,NaN,NaN,gen11,0.223133,0.243414,0.020282
0,7622142,2836,4,44:51.2,00:00.0,NaN,72,13.0,00:00.0,2.0,...,0.095872,1898.025622,0.073903,0.051137,NaN,NaN,gen11,0.240328,0.289555,0.049227
1,7794020,939,4,54:06.9,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.087003,1190.126820,0.086054,0.059545,NaN,NaN,gen11,NaN,0.240849,NaN
3,7893285,7480,4,32:15.1,00:00.0,NaN,72,7.0,00:00.0,1.0,...,0.118288,9035.534923,0.527454,0.223498,NaN,NaN,gen11,NaN,0.267679,NaN
5,7909310,4250,4,49:24.2,00:00.0,NaN,72,7.0,00:00.0,NaN,...,0.147052,2498.144428,0.080999,0.056047,NaN,NaN,gen12,NaN,0.228239,NaN
9,7921215,8116,4,00:03.6,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.184530,3985.168508,0.162935,0.105003,NaN,NaN,gen12,NaN,0.299485,NaN
20,7943045,3871,4,00:37.3,00:00.0,NaN,72,NaN,00:00.0,NaN,...,0.109305,3490.680847,0.162904,0.104983,NaN,NaN,gen12,NaN,0.300010,NaN

In [ ]:
str_filename = 'df_theo_rev.csv'
df.to_csv(f'./output/{str_filename}')