In [1]:
import pandas as pd
import os
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve, auc
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import plotly.express as px

# Pull in Training CSV

In [2]:
str_project = os.getcwd().split('\\')[4]
print(f'Project: {str_project}')
str_task = os.getcwd().split('\\')[5]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('\\')[6]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 06_ml_in_python
Task: 01_home_credit_model
Subtask: 01_data_collection

In [3]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\01_home_credit_model\\01_data_collection'

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

In [23]:
df = pd.read_csv('./input/train.csv')
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,396902,0,Cash loans,F,Y,Y,0,121500,835380,40320.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,112096,0,Cash loans,F,N,Y,0,202500,516069,26478.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,285821,1,Cash loans,M,Y,Y,1,180000,284400,22469.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,376901,0,Cash loans,F,N,Y,0,90000,265536,13685.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,325138,0,Cash loans,F,Y,Y,0,94500,755190,30078.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,7875.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
124996,169482,0,Cash loans,F,N,N,0,180000,661500,17577.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,333982,0,Cash loans,F,N,Y,0,90000,239850,24705.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,320235,0,Cash loans,M,Y,N,0,81000,306000,24305.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# insert row numbers for easy splitting
rownum = range(len(df))
df.insert(0, 'rownum', rownum)
df.head()

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

# Clean data before splitting

In [25]:
missing = df.isnull().mean() * 100
print(missing[missing > 0])
cols_to_remove = missing[missing > 65].index
dfclean = df.drop(columns=cols_to_remove)
numcols = dfclean.select_dtypes(include=['float64','int64']).columns
catcols = dfclean.select_dtypes(include=['object']).columns
dfclean[numcols] = dfclean[numcols].fillna(dfclean[numcols].median())
for col in catcols:
    dfclean[col] = dfclean[col].fillna(dfclean[col].mode()[0])
dfclean

AMT_ANNUITY                    0.0024
AMT_GOODS_PRICE                0.1056
NAME_TYPE_SUITE                0.4488
OWN_CAR_AGE                   65.9352
OCCUPATION_TYPE               31.4336
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     13.4040
AMT_REQ_CREDIT_BUREAU_WEEK    13.4040
AMT_REQ_CREDIT_BUREAU_MON     13.4040
AMT_REQ_CREDIT_BUREAU_QRT     13.4040
AMT_REQ_CREDIT_BUREAU_YEAR    13.4040
Length: 66, dtype: float64

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [26]:
X = dfclean.drop('TARGET', axis=1)
y = dfclean['TARGET']

In [27]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
model = CatBoostClassifier(iterations = 1000, learning_rate=0.1, depth=6, verbose=0)

In [29]:
categorical_columns = dfclean.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']

In [30]:
model.fit(X_train, y_train, cat_features=categorical_columns)

In [32]:
score = model.score(X_valid, y_valid)
print("model accuracy: ", score)

model accuracy:  0.9186

In [38]:
predictions = model.predict_proba(X_valid)
print('Predicted Proba: ', predictions)

Predicted Proba:  [[0.96766975 0.03233025]
 [0.98070588 0.01929412]
 [0.92441696 0.07558304]
 ...
 [0.74918924 0.25081076]
 [0.95219185 0.04780815]
 [0.97458425 0.02541575]]

In [39]:
proba = model.predict_proba(X)[:, 1]

df['probability_default'] = proba
df

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,probability_default
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.027731
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0,0.105439
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,0.607754
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.054737
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.165591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.088933
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,...,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0,0.018572
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.018110
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,...,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0,0.059462
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.172496

In [ ]:
dfwrong = df[['']]

# Split Date into 3 different sets

In [32]:
df_train = dfclean.query('0 <= rownum < 87500')
df_train

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,87495,347233,1,Cash loans,M,Y,Y,1,202500,436500,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
87496,87496,415155,0,Cash loans,F,N,Y,1,90000,325908,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87497,87497,452814,0,Cash loans,M,Y,Y,1,270000,971280,...,0,0,0,0,0.0,0.0,2.0,0.0,0.0,2.0
87498,87498,346541,0,Cash loans,F,N,Y,0,135000,640080,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87499,87499,340871,0,Cash loans,F,N,Y,2,157500,936909,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
df_valid = dfclean.query('87500 <= rownum < 106250')
df_valid

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
87500,87500,356241,1,Cash loans,M,N,Y,0,220500,816660,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
87501,87501,443823,0,Cash loans,F,N,N,0,220500,1535553,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87502,87502,401657,0,Cash loans,M,Y,Y,1,315000,857169,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
87503,87503,145013,0,Cash loans,F,Y,Y,1,112500,697500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87504,87504,231633,0,Cash loans,M,Y,N,1,225000,805536,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106245,106245,140745,0,Cash loans,F,N,N,1,157500,942300,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106246,106246,155170,1,Cash loans,F,N,Y,2,81000,418500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106247,106247,139134,0,Cash loans,F,N,Y,0,112500,1139846,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
106248,106248,188087,0,Cash loans,F,Y,Y,0,166500,472500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
106249,106249,353189,0,Cash loans,F,N,Y,2,99000,755190,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df_test = dfclean.query('rownum >= 106250')
df_test

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
106250,106250,349548,1,Cash loans,F,Y,Y,1,112500,545040,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
106251,106251,115330,1,Cash loans,F,N,Y,1,112500,553806,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
106252,106252,156518,0,Cash loans,M,N,Y,0,126000,269982,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
106253,106253,391420,0,Cash loans,F,Y,Y,0,135000,526491,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106254,106254,351610,0,Cash loans,F,N,Y,2,126000,331632,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

# 1st Model Test

In [47]:
X_train = df_train.drop(columns=['TARGET'])
y_train = df_train['TARGET']

X_valid = df_valid.drop(columns=['TARGET'])
y_valid = df_valid['TARGET']

X_test = df_test.drop(columns=['TARGET'])
y_test = df_test['TARGET']

In [48]:
model = CatBoostClassifier(
    iterations = 1500,
    learning_rate=0.02,
    depth=8,
    verbose=50
)

In [52]:
train_pool = Pool(data=X_train, label=y_train, cat_features=categorical_columns)
valid_pool = Pool(data=X_valid, label=y_valid, cat_features=categorical_columns)

In [53]:
model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

0:	learn: 0.6729234	test: 0.6728810	best: 0.6728810 (0)	total: 123ms	remaining: 3m 3s
50:	learn: 0.2995641	test: 0.2990631	best: 0.2990631 (50)	total: 10.8s	remaining: 5m 5s
100:	learn: 0.2602752	test: 0.2604773	best: 0.2604773 (100)	total: 21.5s	remaining: 4m 57s
150:	learn: 0.2513477	test: 0.2532334	best: 0.2532334 (150)	total: 32.9s	remaining: 4m 53s
200:	learn: 0.2471336	test: 0.2506220	best: 0.2506220 (200)	total: 45.2s	remaining: 4m 52s
250:	learn: 0.2441682	test: 0.2492737	best: 0.2492737 (250)	total: 57.4s	remaining: 4m 45s
300:	learn: 0.2417743	test: 0.2485812	best: 0.2485774 (299)	total: 1m 10s	remaining: 4m 38s
350:	learn: 0.2398584	test: 0.2481638	best: 0.2481610 (349)	total: 1m 22s	remaining: 4m 29s
400:	learn: 0.2380350	test: 0.2479555	best: 0.2479555 (400)	total: 1m 34s	remaining: 4m 18s
450:	learn: 0.2363076	test: 0.2477391	best: 0.2477391 (450)	total: 1m 46s	remaining: 4m 8s
500:	learn: 0.2347189	test: 0.2475530	best: 0.2475529 (499)	total: 1m 58s	remaining: 3m 56s
550:	learn: 0.2328732	test: 0.2473021	best: 0.2472924 (547)	total: 2m 11s	remaining: 3m 45s
600:	learn: 0.2310136	test: 0.2471809	best: 0.2471809 (600)	total: 2m 23s	remaining: 3m 34s
650:	learn: 0.2290993	test: 0.2471182	best: 0.2471182 (650)	total: 2m 35s	remaining: 3m 23s
700:	learn: 0.2271895	test: 0.2470947	best: 0.2470921 (697)	total: 2m 47s	remaining: 3m 11s
750:	learn: 0.2255561	test: 0.2470532	best: 0.2470130 (734)	total: 3m	remaining: 2m 59s
800:	learn: 0.2240195	test: 0.2469474	best: 0.2469111 (795)	total: 3m 13s	remaining: 2m 48s
850:	learn: 0.2223971	test: 0.2468870	best: 0.2468807 (848)	total: 3m 26s	remaining: 2m 37s
900:	learn: 0.2209894	test: 0.2469107	best: 0.2468807 (848)	total: 3m 38s	remaining: 2m 25s
950:	learn: 0.2195536	test: 0.2469146	best: 0.2468807 (848)	total: 3m 50s	remaining: 2m 13s
1000:	learn: 0.2182975	test: 0.2471386	best: 0.2468807 (848)	total: 4m 3s	remaining: 2m 1s
1050:	learn: 0.2168439	test: 0.2470978	best: 0.2468807 (848)	total: 4m 15s	remaining: 1m 49s
1100:	learn: 0.2157036	test: 0.2471995	best: 0.2468807 (848)	total: 4m 27s	remaining: 1m 36s
1150:	learn: 0.2143672	test: 0.2472026	best: 0.2468807 (848)	total: 4m 39s	remaining: 1m 24s
1200:	learn: 0.2130130	test: 0.2471550	best: 0.2468807 (848)	total: 4m 51s	remaining: 1m 12s
1250:	learn: 0.2115809	test: 0.2472251	best: 0.2468807 (848)	total: 5m 4s	remaining: 1m
1300:	learn: 0.2101685	test: 0.2471570	best: 0.2468807 (848)	total: 5m 16s	remaining: 48.4s
1350:	learn: 0.2088230	test: 0.2472429	best: 0.2468807 (848)	total: 5m 28s	remaining: 36.2s
1400:	learn: 0.2073898	test: 0.2476777	best: 0.2468807 (848)	total: 5m 40s	remaining: 24.1s
1450:	learn: 0.2063261	test: 0.2477382	best: 0.2468807 (848)	total: 5m 52s	remaining: 11.9s
1499:	learn: 0.2051956	test: 0.2478071	best: 0.2468807 (848)	total: 6m 4s	remaining: 0us

bestTest = 0.2468807282
bestIteration = 848

Shrink model to first 849 iterations.

In [54]:
y_valid_pred = model.predict(X_valid)
valid_accuracy = accuracy_score(y_valid, y_valid_pred)
print("Validation Accuracy: ", valid_accuracy)

y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test Accuracy: ", test_accuracy)

Validation Accuracy:  0.9199466666666667
Test Accuracy:  0.9195733333333334

In [56]:
feature_importances = model.get_feature_importance()
for feature, importance in zip(X_train.columns, feature_importances):
    print(f'{feature}: {importance}')

rownum: 1.5926634560840978
SK_ID_CURR: 1.376731261380298
NAME_CONTRACT_TYPE: 0.4453918485930486
CODE_GENDER: 2.763813063656411
FLAG_OWN_CAR: 1.4432617520979294
FLAG_OWN_REALTY: 0.29622570679341204
CNT_CHILDREN: 0.488349608737065
AMT_INCOME_TOTAL: 1.5118325860587394
AMT_CREDIT: 3.754783427246804
AMT_ANNUITY: 2.716829370226069
AMT_GOODS_PRICE: 3.809131169402788
NAME_TYPE_SUITE: 0.46167773563669334
NAME_INCOME_TYPE: 1.5657652890270934
NAME_EDUCATION_TYPE: 2.5802463060622736
NAME_FAMILY_STATUS: 1.3311325375482372
NAME_HOUSING_TYPE: 0.6023076340179984
REGION_POPULATION_RELATIVE: 1.291560947180951
DAYS_BIRTH: 4.171291966526367
DAYS_EMPLOYED: 2.291192545927628
DAYS_REGISTRATION: 2.0796549612713853
DAYS_ID_PUBLISH: 2.4784844288231915
FLAG_MOBIL: 0.0
FLAG_EMP_PHONE: 0.008864788443103247
FLAG_WORK_PHONE: 0.8807455861674779
FLAG_CONT_MOBILE: 0.001810092629052294
FLAG_PHONE: 0.5862762705321203
FLAG_EMAIL: 0.07033018829510512
OCCUPATION_TYPE: 1.3069356611194132
CNT_FAM_MEMBERS: 0.5430939935005878
REGION_RATING_CLIENT: 0.728977439299356
REGION_RATING_CLIENT_W_CITY: 0.8399810925136347
WEEKDAY_APPR_PROCESS_START: 0.7497227296224056
HOUR_APPR_PROCESS_START: 1.0176813691317825
REG_REGION_NOT_LIVE_REGION: 0.007500797979153707
REG_REGION_NOT_WORK_REGION: 0.1267004042595308
LIVE_REGION_NOT_WORK_REGION: 0.03965140770204131
REG_CITY_NOT_LIVE_CITY: 0.32653676104871426
REG_CITY_NOT_WORK_CITY: 0.1878917693756833
LIVE_CITY_NOT_WORK_CITY: 0.15932464679209085
ORGANIZATION_TYPE: 2.5446174049552237
EXT_SOURCE_1: 6.09918515476201
EXT_SOURCE_2: 11.425432205890912
EXT_SOURCE_3: 12.583259809821818
APARTMENTS_AVG: 0.5811522357762039
BASEMENTAREA_AVG: 0.3137286190435223
YEARS_BEGINEXPLUATATION_AVG: 0.40518531190724427
ELEVATORS_AVG: 0.25887340610008674
ENTRANCES_AVG: 0.5336431304661629
FLOORSMAX_AVG: 0.35994035001579483
LANDAREA_AVG: 0.4522122042143048
LIVINGAREA_AVG: 0.3860682525015302
NONLIVINGAREA_AVG: 0.5610176854486426
APARTMENTS_MODE: 0.3353222893744758
BASEMENTAREA_MODE: 0.25136879051574074
YEARS_BEGINEXPLUATATION_MODE: 0.22943310103846634
ELEVATORS_MODE: 0.09099628114547019
ENTRANCES_MODE: 0.5062110637227486
FLOORSMAX_MODE: 0.19965813092193122
LANDAREA_MODE: 0.38564803540783327
LIVINGAREA_MODE: 0.3689426501535045
NONLIVINGAREA_MODE: 0.3224655843424223
APARTMENTS_MEDI: 0.49188007304470194
BASEMENTAREA_MEDI: 0.4054514368863774
YEARS_BEGINEXPLUATATION_MEDI: 0.7354274804590769
ELEVATORS_MEDI: 0.134431570320596
ENTRANCES_MEDI: 0.535662111947196
FLOORSMAX_MEDI: 0.2406690139322719
LANDAREA_MEDI: 0.31869646909662147
LIVINGAREA_MEDI: 0.3758398806962338
NONLIVINGAREA_MEDI: 0.5017754503533411
HOUSETYPE_MODE: 0.20633297676312992
TOTALAREA_MODE: 0.4774121660480946
WALLSMATERIAL_MODE: 0.41293892095247486
EMERGENCYSTATE_MODE: 0.043349649811663955
OBS_30_CNT_SOCIAL_CIRCLE: 0.5913394394836338
DEF_30_CNT_SOCIAL_CIRCLE: 1.0488857858372744
OBS_60_CNT_SOCIAL_CIRCLE: 0.4923641364215586
DEF_60_CNT_SOCIAL_CIRCLE: 0.5429798932016168
DAYS_LAST_PHONE_CHANGE: 2.745026287827791
FLAG_DOCUMENT_2: 1.1424975389561987e-05
FLAG_DOCUMENT_3: 1.1094636512611382
FLAG_DOCUMENT_4: 9.153944232202634e-05
FLAG_DOCUMENT_5: 0.008219337137994437
FLAG_DOCUMENT_6: 0.05899441575896356
FLAG_DOCUMENT_7: 0.00012555022851971155
FLAG_DOCUMENT_8: 0.036804308484456975
FLAG_DOCUMENT_9: 0.005446691456006306
FLAG_DOCUMENT_10: 0.0
FLAG_DOCUMENT_11: 0.005398955472820816
FLAG_DOCUMENT_12: 0.0
FLAG_DOCUMENT_13: 0.011961355312227586
FLAG_DOCUMENT_14: 0.03144904026814832
FLAG_DOCUMENT_15: 0.000996362201307864
FLAG_DOCUMENT_16: 0.16114713773367753
FLAG_DOCUMENT_17: 0.0
FLAG_DOCUMENT_18: 0.0565151976283206
FLAG_DOCUMENT_19: 0.003092494884088012
FLAG_DOCUMENT_20: 0.001414804043712167
FLAG_DOCUMENT_21: 0.003722252064413134
AMT_REQ_CREDIT_BUREAU_HOUR: 0.007918004159147117
AMT_REQ_CREDIT_BUREAU_DAY: 0.004627447363995879
AMT_REQ_CREDIT_BUREAU_WEEK: 0.07866059501809453
AMT_REQ_CREDIT_BUREAU_MON: 0.5115807235413157
AMT_REQ_CREDIT_BUREAU_QRT: 0.6970985858567368
AMT_REQ_CREDIT_BUREAU_YEAR: 1.0760830843877693

# 2nd Model Test (removing uneeded columns)

In [57]:
X_train = df_train.drop(columns=['TARGET','rownum','SK_ID_CURR'])
y_train = df_train['TARGET']

X_valid = df_valid.drop(columns=['TARGET','rownum','SK_ID_CURR'])
y_valid = df_valid['TARGET']

X_test = df_test.drop(columns=['TARGET','rownum','SK_ID_CURR'])
y_test = df_test['TARGET']

In [58]:
# adjusting iterations based on previous score
model = CatBoostClassifier(
    iterations = 850,
    learning_rate=0.02,
    depth=8,
    verbose=50
)

In [59]:
train_pool = Pool(data=X_train, label=y_train, cat_features=categorical_columns)
valid_pool = Pool(data=X_valid, label=y_valid, cat_features=categorical_columns)

In [60]:
model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

0:	learn: 0.6722205	test: 0.6721806	best: 0.6721806 (0)	total: 234ms	remaining: 3m 19s
50:	learn: 0.2975143	test: 0.2970210	best: 0.2970210 (50)	total: 11.3s	remaining: 2m 56s
100:	learn: 0.2596416	test: 0.2599759	best: 0.2599759 (100)	total: 21.7s	remaining: 2m 40s
150:	learn: 0.2507620	test: 0.2527962	best: 0.2527962 (150)	total: 34.4s	remaining: 2m 39s
200:	learn: 0.2466342	test: 0.2503498	best: 0.2503498 (200)	total: 47.3s	remaining: 2m 32s
250:	learn: 0.2436371	test: 0.2489926	best: 0.2489926 (250)	total: 59.3s	remaining: 2m 21s
300:	learn: 0.2415000	test: 0.2483251	best: 0.2483147 (299)	total: 1m 10s	remaining: 2m 9s
350:	learn: 0.2396888	test: 0.2478065	best: 0.2478065 (350)	total: 1m 22s	remaining: 1m 57s
400:	learn: 0.2379202	test: 0.2475272	best: 0.2475272 (400)	total: 1m 33s	remaining: 1m 44s
450:	learn: 0.2362104	test: 0.2473537	best: 0.2473537 (450)	total: 1m 45s	remaining: 1m 33s
500:	learn: 0.2344588	test: 0.2471409	best: 0.2471382 (498)	total: 1m 56s	remaining: 1m 21s
550:	learn: 0.2328043	test: 0.2470049	best: 0.2470017 (546)	total: 2m 8s	remaining: 1m 9s
600:	learn: 0.2310501	test: 0.2468145	best: 0.2468145 (600)	total: 2m 20s	remaining: 58.1s
650:	learn: 0.2293743	test: 0.2466672	best: 0.2466431 (648)	total: 2m 32s	remaining: 46.5s
700:	learn: 0.2277797	test: 0.2465729	best: 0.2465729 (700)	total: 2m 44s	remaining: 34.9s
750:	learn: 0.2260440	test: 0.2464032	best: 0.2463927 (749)	total: 2m 56s	remaining: 23.2s
800:	learn: 0.2245546	test: 0.2463921	best: 0.2463606 (785)	total: 3m 8s	remaining: 11.5s
849:	learn: 0.2229901	test: 0.2463283	best: 0.2463273 (848)	total: 3m 19s	remaining: 0us

bestTest = 0.2463273367
bestIteration = 848

Shrink model to first 849 iterations.

In [61]:
y_valid_pred = model.predict(X_valid)
valid_accuracy = accuracy_score(y_valid, y_valid_pred)
print("Validation Accuracy: ", valid_accuracy)

y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test Accuracy: ", test_accuracy)

Validation Accuracy:  0.92016
Test Accuracy:  0.91936

In [62]:
feature_importances = model.get_feature_importance()
for feature, importance in zip(X_train.columns, feature_importances):
    print(f'{feature}: {importance}')

NAME_CONTRACT_TYPE: 0.4680059807630403
CODE_GENDER: 3.0067544224701837
FLAG_OWN_CAR: 1.5003406298751423
FLAG_OWN_REALTY: 0.3023536546649555
CNT_CHILDREN: 0.3408349721745804
AMT_INCOME_TOTAL: 1.6131173783924688
AMT_CREDIT: 3.8145986227351556
AMT_ANNUITY: 2.8780856461931887
AMT_GOODS_PRICE: 4.117806777144479
NAME_TYPE_SUITE: 0.37723869143295974
NAME_INCOME_TYPE: 1.7233387393666362
NAME_EDUCATION_TYPE: 2.5195107086116595
NAME_FAMILY_STATUS: 1.2981405678636202
NAME_HOUSING_TYPE: 0.6775611699854407
REGION_POPULATION_RELATIVE: 1.4224475548076785
DAYS_BIRTH: 4.118241379546655
DAYS_EMPLOYED: 2.9607368414271904
DAYS_REGISTRATION: 1.9138481852666782
DAYS_ID_PUBLISH: 2.4877778581045598
FLAG_MOBIL: 0.0
FLAG_EMP_PHONE: 0.046703208287462744
FLAG_WORK_PHONE: 0.8504918923495861
FLAG_CONT_MOBILE: 0.0020566607914299794
FLAG_PHONE: 0.5135176279720874
FLAG_EMAIL: 0.04178242561475368
OCCUPATION_TYPE: 1.5690946958452228
CNT_FAM_MEMBERS: 0.4188776871738852
REGION_RATING_CLIENT: 0.6690270504174315
REGION_RATING_CLIENT_W_CITY: 0.7358696050194176
WEEKDAY_APPR_PROCESS_START: 0.6657432348285558
HOUR_APPR_PROCESS_START: 1.0857335409952842
REG_REGION_NOT_LIVE_REGION: 0.024583902380256702
REG_REGION_NOT_WORK_REGION: 0.07836820658664395
LIVE_REGION_NOT_WORK_REGION: 0.048419857535243055
REG_CITY_NOT_LIVE_CITY: 0.40270951964957563
REG_CITY_NOT_WORK_CITY: 0.2788471574776711
LIVE_CITY_NOT_WORK_CITY: 0.2890026606965896
ORGANIZATION_TYPE: 2.624393744137375
EXT_SOURCE_1: 6.254244547288362
EXT_SOURCE_2: 11.47538121689546
EXT_SOURCE_3: 13.026539599336253
APARTMENTS_AVG: 0.6450368525347426
BASEMENTAREA_AVG: 0.3307755283863666
YEARS_BEGINEXPLUATATION_AVG: 0.6143058154235488
ELEVATORS_AVG: 0.24777944154512488
ENTRANCES_AVG: 0.5668368745012525
FLOORSMAX_AVG: 0.3907159249128695
LANDAREA_AVG: 0.35179311086235077
LIVINGAREA_AVG: 0.35311784237653765
NONLIVINGAREA_AVG: 0.7191325070634879
APARTMENTS_MODE: 0.4835913079819782
BASEMENTAREA_MODE: 0.4041232079166739
YEARS_BEGINEXPLUATATION_MODE: 0.36958732088832486
ELEVATORS_MODE: 0.12107385065778653
ENTRANCES_MODE: 0.502767814290537
FLOORSMAX_MODE: 0.22696429347206779
LANDAREA_MODE: 0.3948566128964213
LIVINGAREA_MODE: 0.5038627656606556
NONLIVINGAREA_MODE: 0.4454558265505162
APARTMENTS_MEDI: 0.4509930198656014
BASEMENTAREA_MEDI: 0.3708606973435023
YEARS_BEGINEXPLUATATION_MEDI: 0.4434678013623292
ELEVATORS_MEDI: 0.20013708880099004
ENTRANCES_MEDI: 0.3438599011576491
FLOORSMAX_MEDI: 0.08506661553709642
LANDAREA_MEDI: 0.35941232329122486
LIVINGAREA_MEDI: 0.43393055272903386
NONLIVINGAREA_MEDI: 0.4712436478974939
HOUSETYPE_MODE: 0.19175317486854654
TOTALAREA_MODE: 0.3721840161458186
WALLSMATERIAL_MODE: 0.3825521354701322
EMERGENCYSTATE_MODE: 0.029179455350416935
OBS_30_CNT_SOCIAL_CIRCLE: 0.6211758094104869
DEF_30_CNT_SOCIAL_CIRCLE: 1.048526511232618
OBS_60_CNT_SOCIAL_CIRCLE: 0.7686893691754668
DEF_60_CNT_SOCIAL_CIRCLE: 0.5443696055891306
DAYS_LAST_PHONE_CHANGE: 2.931194572870713
FLAG_DOCUMENT_2: 0.000216256143460811
FLAG_DOCUMENT_3: 1.1669825642358094
FLAG_DOCUMENT_4: 5.985283132121428e-05
FLAG_DOCUMENT_5: 0.03641061138322847
FLAG_DOCUMENT_6: 0.05008637364552747
FLAG_DOCUMENT_7: 0.00028538606894797184
FLAG_DOCUMENT_8: 0.051106014659445385
FLAG_DOCUMENT_9: 0.02911676657237516
FLAG_DOCUMENT_10: 0.0
FLAG_DOCUMENT_11: 0.004579114376503587
FLAG_DOCUMENT_12: 0.0
FLAG_DOCUMENT_13: 0.018786142093746325
FLAG_DOCUMENT_14: 0.04011793765369069
FLAG_DOCUMENT_15: 0.0020135658485904906
FLAG_DOCUMENT_16: 0.1879270927153197
FLAG_DOCUMENT_17: 0.0003116823548443392
FLAG_DOCUMENT_18: 0.04751029238829896
FLAG_DOCUMENT_19: 0.004094358801986521
FLAG_DOCUMENT_20: 0.003182326685900714
FLAG_DOCUMENT_21: 0.006619657982267
AMT_REQ_CREDIT_BUREAU_HOUR: 0.03338481675256936
AMT_REQ_CREDIT_BUREAU_DAY: 0.01890348562541648
AMT_REQ_CREDIT_BUREAU_WEEK: 0.06647164231366347
AMT_REQ_CREDIT_BUREAU_MON: 0.41125436808008553
AMT_REQ_CREDIT_BUREAU_QRT: 0.6525554466802054
AMT_REQ_CREDIT_BUREAU_YEAR: 0.8055232259823176

# 3rd Model Test

In [68]:
#change verbose to see effect
model = CatBoostClassifier(
    iterations = 850,
    learning_rate=0.02,
    depth=8,
    verbose=35
)

In [69]:
model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

0:	learn: 0.6722205	test: 0.6721806	best: 0.6721806 (0)	total: 222ms	remaining: 3m 8s
35:	learn: 0.3365833	test: 0.3359562	best: 0.3359562 (35)	total: 8.34s	remaining: 3m 8s
70:	learn: 0.2735547	test: 0.2733151	best: 0.2733151 (70)	total: 15.7s	remaining: 2m 52s
105:	learn: 0.2579998	test: 0.2585067	best: 0.2585067 (105)	total: 23.9s	remaining: 2m 47s
140:	learn: 0.2519564	test: 0.2535666	best: 0.2535666 (140)	total: 32.2s	remaining: 2m 42s
175:	learn: 0.2483644	test: 0.2513249	best: 0.2513249 (175)	total: 41.2s	remaining: 2m 37s
210:	learn: 0.2459094	test: 0.2499834	best: 0.2499834 (210)	total: 51.6s	remaining: 2m 36s
245:	learn: 0.2438728	test: 0.2491259	best: 0.2491259 (245)	total: 1m	remaining: 2m 28s
280:	learn: 0.2423531	test: 0.2485291	best: 0.2485291 (280)	total: 1m 8s	remaining: 2m 19s
315:	learn: 0.2409125	test: 0.2481240	best: 0.2481240 (315)	total: 1m 17s	remaining: 2m 11s
350:	learn: 0.2396888	test: 0.2478065	best: 0.2478065 (350)	total: 1m 26s	remaining: 2m 2s
385:	learn: 0.2384474	test: 0.2476057	best: 0.2476057 (385)	total: 1m 35s	remaining: 1m 54s
420:	learn: 0.2371780	test: 0.2474442	best: 0.2474442 (420)	total: 1m 44s	remaining: 1m 46s
455:	learn: 0.2360003	test: 0.2473077	best: 0.2473077 (455)	total: 1m 54s	remaining: 1m 38s
490:	learn: 0.2348003	test: 0.2471579	best: 0.2471579 (490)	total: 2m 3s	remaining: 1m 30s
525:	learn: 0.2337924	test: 0.2470822	best: 0.2470794 (524)	total: 2m 13s	remaining: 1m 22s
560:	learn: 0.2324055	test: 0.2469536	best: 0.2469536 (560)	total: 2m 22s	remaining: 1m 13s
595:	learn: 0.2312419	test: 0.2468372	best: 0.2468372 (595)	total: 2m 32s	remaining: 1m 4s
630:	learn: 0.2300711	test: 0.2466995	best: 0.2466995 (630)	total: 2m 41s	remaining: 56s
665:	learn: 0.2288227	test: 0.2466534	best: 0.2466431 (648)	total: 2m 50s	remaining: 47s
700:	learn: 0.2277797	test: 0.2465729	best: 0.2465729 (700)	total: 2m 59s	remaining: 38.2s
735:	learn: 0.2266634	test: 0.2464939	best: 0.2464928 (734)	total: 3m 8s	remaining: 29.2s
770:	learn: 0.2253982	test: 0.2463914	best: 0.2463857 (768)	total: 3m 17s	remaining: 20.2s
805:	learn: 0.2244332	test: 0.2464099	best: 0.2463606 (785)	total: 3m 25s	remaining: 11.2s
840:	learn: 0.2232628	test: 0.2463424	best: 0.2463420 (839)	total: 3m 34s	remaining: 2.3s
849:	learn: 0.2229901	test: 0.2463283	best: 0.2463273 (848)	total: 3m 36s	remaining: 0us

bestTest = 0.2463273367
bestIteration = 848

Shrink model to first 849 iterations.

In [70]:
y_valid_pred = model.predict(X_valid)
valid_accuracy = accuracy_score(y_valid, y_valid_pred)
print("Validation Accuracy: ", valid_accuracy)

y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test Accuracy: ", test_accuracy)

Validation Accuracy:  0.92016
Test Accuracy:  0.91936

In [71]:
feature_importances = model.get_feature_importance()
feature_names = X_train.columns

feature_importance_pairs = list(zip(feature_names, feature_importances))
sorted_feature_importance_pairs = sorted(feature_importance_pairs, key=lambda x: x[1], reverse=True)

for feature, importance in sorted_feature_importance_pairs:
    print(f'{feature}: {importance}')

EXT_SOURCE_3: 13.026539599336253
EXT_SOURCE_2: 11.47538121689546
EXT_SOURCE_1: 6.254244547288362
DAYS_BIRTH: 4.118241379546655
AMT_GOODS_PRICE: 4.117806777144479
AMT_CREDIT: 3.8145986227351556
CODE_GENDER: 3.0067544224701837
DAYS_EMPLOYED: 2.9607368414271904
DAYS_LAST_PHONE_CHANGE: 2.931194572870713
AMT_ANNUITY: 2.8780856461931887
ORGANIZATION_TYPE: 2.624393744137375
NAME_EDUCATION_TYPE: 2.5195107086116595
DAYS_ID_PUBLISH: 2.4877778581045598
DAYS_REGISTRATION: 1.9138481852666782
NAME_INCOME_TYPE: 1.7233387393666362
AMT_INCOME_TOTAL: 1.6131173783924688
OCCUPATION_TYPE: 1.5690946958452228
FLAG_OWN_CAR: 1.5003406298751423
REGION_POPULATION_RELATIVE: 1.4224475548076785
NAME_FAMILY_STATUS: 1.2981405678636202
FLAG_DOCUMENT_3: 1.1669825642358094
HOUR_APPR_PROCESS_START: 1.0857335409952842
DEF_30_CNT_SOCIAL_CIRCLE: 1.048526511232618
FLAG_WORK_PHONE: 0.8504918923495861
AMT_REQ_CREDIT_BUREAU_YEAR: 0.8055232259823176
OBS_60_CNT_SOCIAL_CIRCLE: 0.7686893691754668
REGION_RATING_CLIENT_W_CITY: 0.7358696050194176
NONLIVINGAREA_AVG: 0.7191325070634879
NAME_HOUSING_TYPE: 0.6775611699854407
REGION_RATING_CLIENT: 0.6690270504174315
WEEKDAY_APPR_PROCESS_START: 0.6657432348285558
AMT_REQ_CREDIT_BUREAU_QRT: 0.6525554466802054
APARTMENTS_AVG: 0.6450368525347426
OBS_30_CNT_SOCIAL_CIRCLE: 0.6211758094104869
YEARS_BEGINEXPLUATATION_AVG: 0.6143058154235488
ENTRANCES_AVG: 0.5668368745012525
DEF_60_CNT_SOCIAL_CIRCLE: 0.5443696055891306
FLAG_PHONE: 0.5135176279720874
LIVINGAREA_MODE: 0.5038627656606556
ENTRANCES_MODE: 0.502767814290537
APARTMENTS_MODE: 0.4835913079819782
NONLIVINGAREA_MEDI: 0.4712436478974939
NAME_CONTRACT_TYPE: 0.4680059807630403
APARTMENTS_MEDI: 0.4509930198656014
NONLIVINGAREA_MODE: 0.4454558265505162
YEARS_BEGINEXPLUATATION_MEDI: 0.4434678013623292
LIVINGAREA_MEDI: 0.43393055272903386
CNT_FAM_MEMBERS: 0.4188776871738852
AMT_REQ_CREDIT_BUREAU_MON: 0.41125436808008553
BASEMENTAREA_MODE: 0.4041232079166739
REG_CITY_NOT_LIVE_CITY: 0.40270951964957563
LANDAREA_MODE: 0.3948566128964213
FLOORSMAX_AVG: 0.3907159249128695
WALLSMATERIAL_MODE: 0.3825521354701322
NAME_TYPE_SUITE: 0.37723869143295974
TOTALAREA_MODE: 0.3721840161458186
BASEMENTAREA_MEDI: 0.3708606973435023
YEARS_BEGINEXPLUATATION_MODE: 0.36958732088832486
LANDAREA_MEDI: 0.35941232329122486
LIVINGAREA_AVG: 0.35311784237653765
LANDAREA_AVG: 0.35179311086235077
ENTRANCES_MEDI: 0.3438599011576491
CNT_CHILDREN: 0.3408349721745804
BASEMENTAREA_AVG: 0.3307755283863666
FLAG_OWN_REALTY: 0.3023536546649555
LIVE_CITY_NOT_WORK_CITY: 0.2890026606965896
REG_CITY_NOT_WORK_CITY: 0.2788471574776711
ELEVATORS_AVG: 0.24777944154512488
FLOORSMAX_MODE: 0.22696429347206779
ELEVATORS_MEDI: 0.20013708880099004
HOUSETYPE_MODE: 0.19175317486854654
FLAG_DOCUMENT_16: 0.1879270927153197
ELEVATORS_MODE: 0.12107385065778653
FLOORSMAX_MEDI: 0.08506661553709642
REG_REGION_NOT_WORK_REGION: 0.07836820658664395
AMT_REQ_CREDIT_BUREAU_WEEK: 0.06647164231366347
FLAG_DOCUMENT_8: 0.051106014659445385
FLAG_DOCUMENT_6: 0.05008637364552747
LIVE_REGION_NOT_WORK_REGION: 0.048419857535243055
FLAG_DOCUMENT_18: 0.04751029238829896
FLAG_EMP_PHONE: 0.046703208287462744
FLAG_EMAIL: 0.04178242561475368
FLAG_DOCUMENT_14: 0.04011793765369069
FLAG_DOCUMENT_5: 0.03641061138322847
AMT_REQ_CREDIT_BUREAU_HOUR: 0.03338481675256936
EMERGENCYSTATE_MODE: 0.029179455350416935
FLAG_DOCUMENT_9: 0.02911676657237516
REG_REGION_NOT_LIVE_REGION: 0.024583902380256702
AMT_REQ_CREDIT_BUREAU_DAY: 0.01890348562541648
FLAG_DOCUMENT_13: 0.018786142093746325
FLAG_DOCUMENT_21: 0.006619657982267
FLAG_DOCUMENT_11: 0.004579114376503587
FLAG_DOCUMENT_19: 0.004094358801986521
FLAG_DOCUMENT_20: 0.003182326685900714
FLAG_CONT_MOBILE: 0.0020566607914299794
FLAG_DOCUMENT_15: 0.0020135658485904906
FLAG_DOCUMENT_17: 0.0003116823548443392
FLAG_DOCUMENT_7: 0.00028538606894797184
FLAG_DOCUMENT_2: 0.000216256143460811
FLAG_DOCUMENT_4: 5.985283132121428e-05
FLAG_MOBIL: 0.0
FLAG_DOCUMENT_10: 0.0
FLAG_DOCUMENT_12: 0.0

# Model 4 removing all uneeded columns and changing depth

In [35]:
X_train = df_train.drop(columns=['TARGET','rownum','SK_ID_CURR','FLAG_DOCUMENT_12','FLAG_DOCUMENT_10','FLAG_MOBIL','FLAG_DOCUMENT_4','FLAG_DOCUMENT_2','FLAG_DOCUMENT_7','FLAG_DOCUMENT_17','FLAG_DOCUMENT_15','FLAG_CONT_MOBILE','FLAG_DOCUMENT_20','FLAG_DOCUMENT_19','FLAG_DOCUMENT_11','FLAG_DOCUMENT_21'])
y_train = df_train['TARGET']

X_valid = df_valid.drop(columns=['TARGET','rownum','SK_ID_CURR','FLAG_DOCUMENT_12','FLAG_DOCUMENT_10','FLAG_MOBIL','FLAG_DOCUMENT_4','FLAG_DOCUMENT_2','FLAG_DOCUMENT_7','FLAG_DOCUMENT_17','FLAG_DOCUMENT_15','FLAG_CONT_MOBILE','FLAG_DOCUMENT_20','FLAG_DOCUMENT_19','FLAG_DOCUMENT_11','FLAG_DOCUMENT_21'])
y_valid = df_valid['TARGET']

X_test = df_test.drop(columns=['TARGET','rownum','SK_ID_CURR','FLAG_DOCUMENT_12','FLAG_DOCUMENT_10','FLAG_MOBIL','FLAG_DOCUMENT_4','FLAG_DOCUMENT_2','FLAG_DOCUMENT_7','FLAG_DOCUMENT_17','FLAG_DOCUMENT_15','FLAG_CONT_MOBILE','FLAG_DOCUMENT_20','FLAG_DOCUMENT_19','FLAG_DOCUMENT_11','FLAG_DOCUMENT_21'])
y_test = df_test['TARGET']

In [36]:
train_pool = Pool(data=X_train, label=y_train, cat_features=categorical_columns)
valid_pool = Pool(data=X_valid, label=y_valid, cat_features=categorical_columns)

In [37]:
#changing depth to see effect
model = CatBoostClassifier(
    iterations = 830,
    learning_rate=0.02,
    depth=6,
    verbose=35
)

In [38]:
model.fit(
    train_pool,
    eval_set=valid_pool,
    use_best_model=True
)

0:	learn: 0.6730612	test: 0.6730374	best: 0.6730374 (0)	total: 176ms	remaining: 2m 26s
35:	learn: 0.3391094	test: 0.3382413	best: 0.3382413 (35)	total: 5.78s	remaining: 2m 7s
70:	learn: 0.2762115	test: 0.2752073	best: 0.2752073 (70)	total: 10.9s	remaining: 1m 56s
105:	learn: 0.2606863	test: 0.2598246	best: 0.2598246 (105)	total: 16s	remaining: 1m 49s
140:	learn: 0.2549378	test: 0.2544455	best: 0.2544455 (140)	total: 21.2s	remaining: 1m 43s
175:	learn: 0.2521063	test: 0.2519974	best: 0.2519974 (175)	total: 26.5s	remaining: 1m 38s
210:	learn: 0.2503839	test: 0.2507218	best: 0.2507218 (210)	total: 31.9s	remaining: 1m 33s
245:	learn: 0.2490546	test: 0.2498362	best: 0.2498362 (245)	total: 37.7s	remaining: 1m 29s
280:	learn: 0.2479796	test: 0.2492059	best: 0.2492059 (280)	total: 43.1s	remaining: 1m 24s
315:	learn: 0.2470473	test: 0.2487691	best: 0.2487691 (315)	total: 48.4s	remaining: 1m 18s
350:	learn: 0.2462998	test: 0.2484240	best: 0.2484240 (350)	total: 53.7s	remaining: 1m 13s
385:	learn: 0.2456235	test: 0.2481585	best: 0.2481585 (385)	total: 58.8s	remaining: 1m 7s
420:	learn: 0.2449082	test: 0.2478776	best: 0.2478766 (419)	total: 1m 4s	remaining: 1m 2s
455:	learn: 0.2442713	test: 0.2476051	best: 0.2476037 (453)	total: 1m 9s	remaining: 56.7s
490:	learn: 0.2436112	test: 0.2474277	best: 0.2474277 (490)	total: 1m 14s	remaining: 51.3s
525:	learn: 0.2429470	test: 0.2472093	best: 0.2472093 (525)	total: 1m 19s	remaining: 45.9s
560:	learn: 0.2423766	test: 0.2470556	best: 0.2470556 (560)	total: 1m 24s	remaining: 40.6s
595:	learn: 0.2417624	test: 0.2469106	best: 0.2469106 (595)	total: 1m 29s	remaining: 35.3s
630:	learn: 0.2411625	test: 0.2467815	best: 0.2467815 (630)	total: 1m 35s	remaining: 30.1s
665:	learn: 0.2405035	test: 0.2466665	best: 0.2466665 (665)	total: 1m 40s	remaining: 24.8s
700:	learn: 0.2398796	test: 0.2465815	best: 0.2465815 (700)	total: 1m 45s	remaining: 19.5s
735:	learn: 0.2393440	test: 0.2464919	best: 0.2464919 (735)	total: 1m 51s	remaining: 14.2s
770:	learn: 0.2387443	test: 0.2463956	best: 0.2463913 (769)	total: 1m 56s	remaining: 8.9s
805:	learn: 0.2382321	test: 0.2463575	best: 0.2463459 (801)	total: 2m 1s	remaining: 3.63s
829:	learn: 0.2378664	test: 0.2462975	best: 0.2462941 (828)	total: 2m 5s	remaining: 0us

bestTest = 0.2462940978
bestIteration = 828

Shrink model to first 829 iterations.

In [39]:
y_valid_pred = model.predict(X_valid)
valid_accuracy = accuracy_score(y_valid, y_valid_pred)
print("Validation Accuracy: ", valid_accuracy)

y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test Accuracy: ", test_accuracy)

Validation Accuracy:  0.9202133333333333
Test Accuracy:  0.91952

In [40]:
feature_importances = model.get_feature_importance()
feature_names = X_train.columns

feature_importance_pairs = list(zip(feature_names, feature_importances))
sorted_feature_importance_pairs = sorted(feature_importance_pairs, key=lambda x: x[1], reverse=True)

for feature, importance in sorted_feature_importance_pairs:
    print(f'{feature}: {importance}')

EXT_SOURCE_3: 18.818595456346753
EXT_SOURCE_2: 16.78164097948164
EXT_SOURCE_1: 7.418011057681205
AMT_GOODS_PRICE: 4.322177514058808
AMT_CREDIT: 4.234384110174529
DAYS_BIRTH: 3.903090013176055
NAME_EDUCATION_TYPE: 3.3360612296512144
CODE_GENDER: 2.967514028258597
DAYS_EMPLOYED: 2.4525804103763424
AMT_ANNUITY: 2.2089946291995717
ORGANIZATION_TYPE: 2.087685112754076
DAYS_LAST_PHONE_CHANGE: 1.9414888468363305
DAYS_ID_PUBLISH: 1.8984547856628906
FLAG_OWN_CAR: 1.4841652259996467
NAME_INCOME_TYPE: 1.4764655492984309
DAYS_REGISTRATION: 1.298885341426827
FLAG_DOCUMENT_3: 1.2959907446027188
OCCUPATION_TYPE: 1.1236888748648834
DEF_30_CNT_SOCIAL_CIRCLE: 1.0457034820575404
NAME_FAMILY_STATUS: 1.027638126626132
FLAG_WORK_PHONE: 0.7597087114319682
REGION_RATING_CLIENT_W_CITY: 0.7557667893018376
REGION_POPULATION_RELATIVE: 0.7141828947356571
AMT_INCOME_TOTAL: 0.6382139478192671
DEF_60_CNT_SOCIAL_CIRCLE: 0.5954364573657119
YEARS_BEGINEXPLUATATION_MEDI: 0.5503709774626889
REGION_RATING_CLIENT: 0.5359011148012274
AMT_REQ_CREDIT_BUREAU_YEAR: 0.5254511146108056
FLAG_PHONE: 0.5231788259469379
AMT_REQ_CREDIT_BUREAU_QRT: 0.4920849568164062
OBS_60_CNT_SOCIAL_CIRCLE: 0.49089032598437093
NAME_HOUSING_TYPE: 0.4531661042073731
HOUR_APPR_PROCESS_START: 0.43731918447283874
YEARS_BEGINEXPLUATATION_AVG: 0.4303609562353426
NONLIVINGAREA_MODE: 0.4280438839479299
APARTMENTS_AVG: 0.41115641958074634
NAME_CONTRACT_TYPE: 0.3939848805213553
NONLIVINGAREA_AVG: 0.37099433948368904
BASEMENTAREA_MEDI: 0.352815711831468
ENTRANCES_AVG: 0.3521847162613064
AMT_REQ_CREDIT_BUREAU_MON: 0.3439285275751075
OBS_30_CNT_SOCIAL_CIRCLE: 0.3431537932801236
LIVINGAREA_AVG: 0.31750849927385966
TOTALAREA_MODE: 0.315780051586707
ENTRANCES_MEDI: 0.3012034954039852
WEEKDAY_APPR_PROCESS_START: 0.29504767787667974
YEARS_BEGINEXPLUATATION_MODE: 0.29449923476239925
REG_CITY_NOT_WORK_CITY: 0.2911022835257867
APARTMENTS_MEDI: 0.2870013554470642
BASEMENTAREA_MODE: 0.28528269236536064
REG_CITY_NOT_LIVE_CITY: 0.2750768914426668
NONLIVINGAREA_MEDI: 0.27500625485750846
ENTRANCES_MODE: 0.27187955166344246
LIVINGAREA_MEDI: 0.2587925262790942
FLAG_EMP_PHONE: 0.2512733026734186
FLAG_DOCUMENT_16: 0.24316737021311016
LIVINGAREA_MODE: 0.23524837436918833
LANDAREA_AVG: 0.22813063136173825
HOUSETYPE_MODE: 0.22490466671393347
LIVE_CITY_NOT_WORK_CITY: 0.22163532292398674
FLOORSMAX_MEDI: 0.21775291357084053
LANDAREA_MODE: 0.21565561619961687
CNT_FAM_MEMBERS: 0.21188420507572542
APARTMENTS_MODE: 0.19669464990824095
FLOORSMAX_AVG: 0.18835287439610687
NAME_TYPE_SUITE: 0.18410886390286663
LANDAREA_MEDI: 0.17600189730121213
FLOORSMAX_MODE: 0.17124669624201874
ELEVATORS_MODE: 0.16626191521234557
FLAG_OWN_REALTY: 0.16300652670798393
BASEMENTAREA_AVG: 0.14054607715540401
CNT_CHILDREN: 0.13123093335298414
ELEVATORS_AVG: 0.11790451610405016
FLAG_DOCUMENT_18: 0.11534086430421303
WALLSMATERIAL_MODE: 0.08591864095130022
FLAG_DOCUMENT_6: 0.08369064880163987
ELEVATORS_MEDI: 0.07339591911293261
FLAG_DOCUMENT_14: 0.07312509151845815
REG_REGION_NOT_WORK_REGION: 0.07033193861545035
AMT_REQ_CREDIT_BUREAU_WEEK: 0.04875007610680606
FLAG_DOCUMENT_13: 0.046709970385354765
EMERGENCYSTATE_MODE: 0.04393759372657846
AMT_REQ_CREDIT_BUREAU_HOUR: 0.03973391686742407
REG_REGION_NOT_LIVE_REGION: 0.029025046006399376
LIVE_REGION_NOT_WORK_REGION: 0.027609723842021067
FLAG_DOCUMENT_8: 0.026540462872463075
FLAG_DOCUMENT_5: 0.022295608487138126
FLAG_DOCUMENT_9: 0.021475076674486802
AMT_REQ_CREDIT_BUREAU_DAY: 0.010001217533193989
FLAG_EMAIL: 0.0074201841165248365

In [41]:
predictions = model.predict_proba(X_valid)
print("Predicted Probability: ", predictions)

Predicted Probability:  [[0.85085184 0.14914816]
 [0.97595952 0.02404048]
 [0.94523549 0.05476451]
 ...
 [0.94999231 0.05000769]
 [0.95552576 0.04447424]
 [0.72930223 0.27069777]]

# Finished with CatBoost Modeling FINAL SCORES: 
# Validation accuracy: 92.02% | Test accuracy: 91.95%

# Logistic Regression Modeling

In [8]:
categorical_columns = dfclean.select_dtypes(include=['object', 'category']).columns.tolist()

In [9]:
dfclean = pd.get_dummies(dfclean, columns=categorical_columns, drop_first=True)

In [10]:
X = dfclean.drop('TARGET', axis = 1)
y = dfclean['TARGET']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
x_test = scaler.transform(X_test)

In [13]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=100)

In [14]:
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [15]:
y_pred = model.predict(X_test)

C:\Users\bhyde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [16]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.40636
Confusion Matrix:
 [[ 8747 14240]
 [  601  1412]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.38      0.54     22987
           1       0.09      0.70      0.16      2013

    accuracy                           0.41     25000
   macro avg       0.51      0.54      0.35     25000
weighted avg       0.87      0.41      0.51     25000

In [17]:
# find best model for Logistic Regression
#def eval_model(C, solver, penalty):
#    try:
#        model = LogisticRegression(C=C, solver=solver, penalty=penalty, max_iter=1000)
#        model.fit(X_train, y_train)
#        y_pred = model.predict(X_test)
#        accuracy = accuracy_score(y_test, y_pred)
#        print(f"Accuracy with C={C}, solver={solver}, penalty={penalty}: {accuracy}")
#        print("Classification Report:\n", classification_report(y_test, y_pred))
#        return model, accuracy
#    except Exception as e:
#        print(f"Error with C={C}, solver={solver}, penalty={penalty}: {e}")
#        return None, 0

In [18]:
#best_accuracy = 0
#best_model = None
#hyperparams = [
#    (C, solver, penalty)
#    for C in [0.01, 0.1, 1, 10, 100]
#    for solver in ['liblinear', 'newton-cg', 'lbfgs', 'saga']
#    for penalty in ['l2', 'l1']
#    if not (solver in ['newton-cg', 'lbfgs'] and penalty == 'l1')
#]

#for C, solver, penalty in hyperparams:
#    model, accuracy = eval_model(C, solver, penalty)
#    if accuracy > best_accuracy:
#        best_accuracy = accuracy
#        best_model = model

In [17]:
# best model: C= 0.01, solver=liblinear, penalty=l1
model = LogisticRegression(solver='liblinear', C=0.01, penalty='l1', max_iter=1000)

In [18]:
model.fit(X_train, y_train)

LogisticRegression(C=0.01, max_iter=1000, penalty='l1', solver='liblinear')

In [19]:
y_pred = model.predict(X_test)

C:\Users\bhyde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [20]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.91948
Confusion Matrix:
 [[22987     0]
 [ 2013     0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      1.00      0.96     22987
           1       0.00      0.00      0.00      2013

    accuracy                           0.92     25000
   macro avg       0.46      0.50      0.48     25000
weighted avg       0.85      0.92      0.88     25000

C:\Users\bhyde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\bhyde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\bhyde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [42]:
y_score = model.predict_proba(X)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_score)

fig = px.area(
    x=fpr, y=tpr,
    title=f'ROC CURVE(AUC={auc(fpr, tpr):.4f})',
    width=700, height=500
)
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_xaxes(constrain='domain')
fig.show()

CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=4]="Y": Cannot convert 'b'Y'' to float

In [8]:
df_train_log = dfclean.query('0 <= rownum < 87500')
df_train_log

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,87495,347233,1,Cash loans,M,Y,Y,1,202500,436500,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
87496,87496,415155,0,Cash loans,F,N,Y,1,90000,325908,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87497,87497,452814,0,Cash loans,M,Y,Y,1,270000,971280,...,0,0,0,0,0.0,0.0,2.0,0.0,0.0,2.0
87498,87498,346541,0,Cash loans,F,N,Y,0,135000,640080,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87499,87499,340871,0,Cash loans,F,N,Y,2,157500,936909,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [9]:
df_test_log = dfclean.query('rownum >= 87500')
df_test_log

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
87500,87500,356241,1,Cash loans,M,N,Y,0,220500,816660,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
87501,87501,443823,0,Cash loans,F,N,N,0,220500,1535553,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87502,87502,401657,0,Cash loans,M,Y,Y,1,315000,857169,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
87503,87503,145013,0,Cash loans,F,Y,Y,1,112500,697500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87504,87504,231633,0,Cash loans,M,Y,N,1,225000,805536,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0