In [1]:
import os
import pandas as pd
import numpy as np

### Functions

In [2]:
def get_pd_tier(flt_ecnl_mod, flt_lgd, flt_intercept, flt_coef):
    flt_pd_tier = ((flt_ecnl_mod - flt_intercept) / flt_coef) / flt_lgd
    return flt_pd_tier

### Constants

In [3]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')
str_dirname_output = './output'
str_variant = 'noPTImodel7'

# constants
flt_lgd_constant = 0.4324
flt_intercept_mike = -0.03281
flt_coef_mike = 1.95553

# tier thresholds
dict_tier_thresholds = {
    'A1': 0.04,
    'A': 0.07,
    'B': 0.14,
    'C': 0.17,
    'D': 0.2015,
}

Project: 20231010-gen-xii
Task: ad_hoc

### Output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Variant directory

In [5]:
try:
    os.mkdir(f'{str_dirname_output}/{str_variant}')
except:
    pass

### Tier thresholds

In [6]:
df = pd.DataFrame({
    'tier': list(dict_tier_thresholds.keys()),
    'ecnl_mod_thresh': list(dict_tier_thresholds.values()),
})
df

  tier  ecnl_mod_thresh
0   A1           0.0400
1    A           0.0700
2    B           0.1400
3    C           0.1700
4    D           0.2015

### Get thresholds based on PD

In [7]:
df['pd_thresh'] = df['ecnl_mod_thresh'].apply(
    lambda x: get_pd_tier(
        flt_ecnl_mod=x, 
        flt_lgd=flt_lgd_constant, 
        flt_intercept=flt_intercept_mike, 
        flt_coef=flt_coef_mike,
    ),
)
df

  tier  ecnl_mod_thresh  pd_thresh
0   A1           0.0400   0.086107
1    A           0.0700   0.121586
2    B           0.1400   0.204371
3    C           0.1700   0.239850
4    D           0.2015   0.277103

### Save

In [8]:
str_filename = 'df_pd_tiers.csv'
str_local_path = f'{str_dirname_output}/{str_variant}/{str_filename}'
df.to_csv(str_local_path, index=False)