In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import pyodbc
import numpy as np
import pickle

### FUNCTIONS

In [2]:
def read_sql_script(str_local_path):
    str_query = open(str_local_path, 'r').read()
    return str_query

In [3]:
def pull_data_from_sql(str_query, conn, bool_close_conn=True):
    df = pd.read_sql_query(
        sql=str_query,
        con=conn,
    )
    if bool_close_conn:
        conn.close()
    else:
        pass
    return df

In [4]:
class GetData:
    def __init__(self):
        pass
    def read_sql_script(self, str_local_path):
        str_query = open(str_local_path, 'r').read()
        # save to object
        self.str_query = str_query
        # return object
        return self
    def pull_data_from_sql(self, conn, bool_close_conn=True):
        df = pd.read_sql_query(
            sql=self.str_query,
            con=conn,
        )
        if bool_close_conn:
            conn.close()
        else:
            pass
        return df

### CONSTANTS

In [5]:
str_project = os.getcwd().split('\\')[3]
print(f'Project: {str_project}')

str_task = os.getcwd().split('\\')[4]
print(f'Task: {str_task}')

str_subtask = os.getcwd().split('\\')[5]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 20240521_bridger_internship
Task: 03_python
Subtask: 01_jupyter_practice

In [6]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

### READ SQL

In [7]:
# initialize class To create df_check
cls_get_data = GetData()

#read query
str_filename = 'GenScoresTable2024.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_check = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df_check

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7463119,3416,2024-01-02 10:50:16.100,2024-01-16,72,13.0,B,22692.05,20.49,479.0,0.074451,0.135543,Gen11
1,7537832,5654,2024-02-01 17:10:31.693,2024-02-06,66,7.0,A1,17809.00,18.74,569.0,-0.016412,0.013493,Gen11
2,7808778,4892,2024-04-20 15:59:20.183,2024-04-22,72,NaN,B,17565.50,24.67,471.0,0.111494,0.147749,Gen11
3,7445683,4993,2023-12-23 09:13:16.957,2024-01-04,72,NaN,B,18934.36,22.00,618.0,0.068107,0.104364,Gen11
4,7651391,4625,2024-03-11 17:43:57.173,2024-03-21,72,NaN,C,27291.41,23.25,533.0,0.144349,0.123361,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7474362,6528,2024-01-06 11:46:21.517,2024-01-15,72,13.0,A1,24509.73,19.24,643.0,0.009927,0.051097,Gen11
9707,7476716,1520,2024-01-08 09:40:11.703,2024-01-25,60,7.0,D,14652.91,29.24,585.0,0.189745,0.477473,Gen11
9708,7496220,7925,2024-01-16 14:02:31.207,2024-01-18,48,NaN,B,15996.00,22.45,432.0,0.101922,0.145866,Gen11
9709,7543543,857,2024-02-03 13:56:26.593,2024-02-15,60,NaN,D,17801.54,28.24,707.0,0.189315,0.167826,Gen11
9710,7705267,6272,2024-03-25 11:44:18.710,2024-04-01,72,NaN,B,13799.11,26.74,490.0,0.139115,0.177943,Gen11

### TempStaticPool & Account

In [9]:
# initialize class And gather data from tempstaticpool and account tables
cls_get_data = GetData()

#read query
str_filename = 'TblTempAndAcc.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_part1half = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df_part1half

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico
0,7134678,2833,2023-09-26 14:02:56.557,2023-10-16,72,NaN,B,22678.48,24.24,530.0
1,6870356,4462,2023-06-07 18:04:07.950,2023-06-23,72,NaN,B,20615.54,24.74,509.0
2,7026175,1325,2023-08-11 14:42:27.830,2023-08-18,48,7.0,A1,8010.90,18.74,553.0
3,7257373,7637,2023-10-21 14:14:36.717,2023-10-26,72,NaN,B,20360.10,24.24,501.0
4,7378866,7741,2023-11-29 10:52:26.653,2023-12-27,72,NaN,B,25062.93,24.24,631.0
...,...,...,...,...,...,...,...,...,...,...
24917,7078235,2314,2023-09-02 08:10:43.797,2023-11-13,72,13.0,A1,24712.26,19.24,557.0
24918,7089924,5846,2023-09-07 16:02:59.337,2023-09-22,72,7.0,B,18036.80,23.24,571.0
24919,7268891,6642,2023-10-23 09:32:42.723,2023-10-30,66,NaN,B,19563.72,22.74,456.0
24920,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0
24921,7402714,6507,2023-12-08 16:31:17.473,2023-12-12,72,NaN,B,21920.56,18.00,539.0

In [10]:
df_part1 = df_part1half[df_part1half['dtmFunded']>= '2024-01-01']
df_part1

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico
5,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0
6,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0
7,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0
8,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0
77,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0
...,...,...,...,...,...,...,...,...,...,...
24893,7564783,6187,2024-02-12 14:06:04.553,2024-02-22,66,NaN,C,18260.00,25.74,499.0
24894,7670991,4229,2024-03-19 12:41:07.250,2024-04-01,72,NaN,A,14845.10,19.24,644.0
24895,7721327,6605,2024-04-01 10:55:15.323,2024-04-24,72,13.0,B,23668.50,22.24,557.0
24896,7827471,5171,2024-04-29 15:05:15.953,2024-05-29,72,7.0,D,30369.44,25.00,526.0
24920,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0

### DimScoreCard Gen 11 query

In [11]:
# initialize class and gather data from the dimscorecard table
cls_get_data = GetData()

#read query
str_filename = 'DimScoreCardGen11.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_part2 = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df_part2

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,intAccountKey,fltDebtorScore,dtmStampCreation,strScoreCardVersion
0,6855060,0.139762,2023-06-01 00:00:17.823,genxi_v2_2
1,6855450,0.053856,2023-06-01 00:00:49.190,genxi_v2_2
2,6855505,0.397769,2023-06-01 00:00:51.427,genxi_v2_2
3,6855501,0.131117,2023-06-01 00:01:48.493,genxi_v2_2
4,6855506,0.187866,2023-06-01 00:01:55.847,genxi_v2_2
...,...,...,...,...
1671714,7189419,0.069399,2023-10-11 13:42:47.007,genxi_v2_2
1671715,7189419,0.069399,2023-10-11 13:42:57.220,genxi_v2_2
1671716,7189421,0.185430,2023-10-11 13:43:25.040,genxi_v2_2
1671717,7189422,0.171050,2023-10-11 13:43:25.757,genxi_v2_2
1671718,7185144,0.063212,2023-10-11 13:43:29.903,genxi_v2_2

In [32]:

df_sort = df_part2.sort_values(by=['dtmStampCreation'], ascending=[False])
df_sorted = df_sort.drop_duplicates(subset=['intAccountKey'], keep='first')
df_sorted.rename(columns = {'fltDebtorScore' : 'Gen 11 Score'}, inplace=True)
df_sorted

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\1425707308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sorted.rename(columns = {'fltDebtorScore' : 'Gen 11 Score'}, inplace=True)

,intAccountKey,Gen 11 Score,dtmStampCreation,strScoreCardVersion
1360221,7910607,0.121273,2024-06-05 03:21:14.853,genxi_v2_3
1360220,7910605,0.365003,2024-06-05 03:19:32.397,genxi_v2_3
1360219,7910604,0.288985,2024-06-05 03:18:59.383,genxi_v2_3
1360218,7910603,0.117900,2024-06-05 03:18:25.907,genxi_v2_3
1360215,7910601,0.115811,2024-06-05 03:05:24.850,genxi_v2_3
...,...,...,...,...
8,6855507,0.118228,2023-06-01 00:02:08.017,genxi_v2_2
7,6855506,0.177180,2023-06-01 00:02:06.273,genxi_v2_2
6,6855418,0.075651,2023-06-01 00:02:03.810,genxi_v2_2
3,6855501,0.131117,2023-06-01 00:01:48.493,genxi_v2_2
2,6855505,0.397769,2023-06-01 00:00:51.427,genxi_v2_2

### Gen 12 DimScoreCard

In [13]:
# initialize class and gather data from the dimscorecard table
cls_get_data = GetData()

#read query
str_filename = 'DimScoreCardGen12.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_part3 = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

In [33]:
df_sort2 = df_part3.sort_values(by=['dtmStampCreation'], ascending=[False])
df_sorted2 = df_sort2.drop_duplicates(subset=['intAccountKey'], keep='first')
df_sorted2.rename(columns= {'fltDebtorScore': 'Gen 12 Score'}, inplace=True)
df_sorted2

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\1383975919.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sorted2.rename(columns= {'fltDebtorScore': 'Gen 12 Score'}, inplace=True)

,intAccountKey,Gen 12 Score,dtmStampCreation,strScoreCardVersion
531050,7898242,0.262808,2024-05-30 21:25:45.650,genxii_v2
531049,7898668,0.405060,2024-05-30 21:25:29.317,genxii_v2
531048,7895139,0.268158,2024-05-30 21:25:23.687,genxii_v2
531047,7897713,0.285327,2024-05-30 21:25:16.423,genxii_v2
531045,7898663,0.301386,2024-05-30 21:24:53.240,genxii_v2
...,...,...,...,...
1107,7374147,0.270598,2023-11-27 20:24:14.760,genxii
1105,7374145,0.197009,2023-11-27 20:24:04.413,genxii
1104,7374144,0.176524,2023-11-27 20:23:49.170,genxii
1102,7374143,0.134068,2023-11-27 20:23:39.930,genxii
1094,7374141,0.323379,2023-11-27 20:22:53.307,genxii

In [62]:
df_genmerge = pd.merge(df_part2, df_part3, left_on=['intAccountKey','dtmStampCreation'],right_on=['intAccountKey','dtmStampCreation'], how='left')
df_genmerge
#df_genmerge.rename(columns = {'fltDebtorScore_x' : 'Gen 11 Score'}, inplace = True)
#df_genmerge.rename(columns = {'fltDebtorScore_y' : 'Gen 12 Score'}, inplace = True)
#df_genmerge.drop(columns ='strScoreCardVersion_x', inplace=True)
#df_genmerge.drop(columns ='strScoreCardVersion_y', inplace=True)
#df_genmerge.drop(columns ='dtmStampCreation_y', inplace=True)
#df_genmerge.sort_values(by=['dtmStampCreation_x'], ascending=[False])
#df_dropdup = df_genmerge.drop_duplicates(subset=['intAccountKey'], keep='first')
#df_dropdup

,intAccountKey,fltDebtorScore_x,dtmStampCreation,strScoreCardVersion_x,fltDebtorScore_y,strScoreCardVersion_y
0,6855060,0.139762,2023-06-01 00:00:17.823,genxi_v2_2,NaN,NaN
1,6855450,0.053856,2023-06-01 00:00:49.190,genxi_v2_2,NaN,NaN
2,6855505,0.397769,2023-06-01 00:00:51.427,genxi_v2_2,NaN,NaN
3,6855501,0.131117,2023-06-01 00:01:48.493,genxi_v2_2,NaN,NaN
4,6855506,0.187866,2023-06-01 00:01:55.847,genxi_v2_2,NaN,NaN
...,...,...,...,...,...,...
1671714,7189419,0.069399,2023-10-11 13:42:47.007,genxi_v2_2,NaN,NaN
1671715,7189419,0.069399,2023-10-11 13:42:57.220,genxi_v2_2,NaN,NaN
1671716,7189421,0.185430,2023-10-11 13:43:25.040,genxi_v2_2,NaN,NaN
1671717,7189422,0.171050,2023-10-11 13:43:25.757,genxi_v2_2,NaN,NaN
1671718,7185144,0.063212,2023-10-11 13:43:29.903,genxi_v2_2,NaN,NaN

In [36]:
df_dropdup.rename(columns={'dtmStampCreation_x': 'dtmStampCreation'}, inplace=True)

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7712\3111834302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropdup.rename(columns={'dtmStampCreation_x': 'dtmStampCreation'}, inplace=True)

In [37]:
df_dropdup

         intAccountKey  Gen 11 Score        dtmStampCreation  Gen 12 Score
0              7351597      0.076162 2023-11-17 03:41:14.900      0.048524
8              7351454      0.017240 2023-11-17 04:02:44.563      0.234694
30             7326585      0.152899 2023-11-17 13:55:11.433      0.158715
32             7351632      0.122925 2023-11-17 14:02:18.457      0.098854
38             7350789      0.207903 2023-11-17 14:09:15.987      0.229302
...                ...           ...                     ...           ...
7489654        7834934      0.196831 2024-05-02 22:06:52.610      0.319744
7489674        7834936      0.131145 2024-05-02 22:07:17.043      0.059058
7489678        7834937      0.202200 2024-05-02 22:08:34.053      0.087510
7489679        7834941      0.146706 2024-05-02 22:09:41.833      0.129186
7489683        7834942      0.158928 2024-05-02 22:10:19.890      0.128861

[327245 rows x 4 columns]

In [38]:
df_fullmerge = pd.merge(df_part1, df_dropdup, left_on='bigAccountId', right_on='intAccountKey', how='left')
df_fullmerge

,bigAccountId,bigDealerId,dtmStampCreation_x,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,intAccountKey,Gen 11 Score,dtmStampCreation_y,Gen 12 Score
0,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0,7724580.0,0.144020,2024-04-02 20:17:58.670,0.229042
1,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0,7729737.0,0.164120,2024-04-04 21:43:27.003,0.091615
2,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0,7892756.0,0.072356,2024-05-28 18:51:05.593,0.111799
3,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0,7532311.0,0.212668,2024-01-31 00:35:07.293,0.161462
4,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0,7443845.0,0.069505,2023-12-22 19:37:42.077,0.099460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7564783,6187,2024-02-12 14:06:04.553,2024-02-22,66,NaN,C,18260.00,25.74,499.0,7564783.0,0.126331,2024-02-12 21:06:24.883,0.163068
9707,7670991,4229,2024-03-19 12:41:07.250,2024-04-01,72,NaN,A,14845.10,19.24,644.0,7670991.0,0.055343,2024-03-19 18:41:16.367,0.034021
9708,7721327,6605,2024-04-01 10:55:15.323,2024-04-24,72,13.0,B,23668.50,22.24,557.0,7721327.0,0.117213,2024-04-01 16:55:24.813,0.075132
9709,7827471,5171,2024-04-29 15:05:15.953,2024-05-29,72,7.0,D,30369.44,25.00,526.0,7827471.0,0.156908,2024-05-03 16:47:42.313,0.219028
9710,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0,7358901.0,0.179799,2023-12-19 17:12:23.133,0.244204

In [39]:
df_fullmergenew = df_fullmerge[df_fullmerge['dtmFunded'] >= '2024-01-01']
df_fullmergenew

,bigAccountId,bigDealerId,dtmStampCreation_x,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,intAccountKey,Gen 11 Score,dtmStampCreation_y,Gen 12 Score
0,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0,7724580.0,0.144020,2024-04-02 20:17:58.670,0.229042
1,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0,7729737.0,0.164120,2024-04-04 21:43:27.003,0.091615
2,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0,7892756.0,0.072356,2024-05-28 18:51:05.593,0.111799
3,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0,7532311.0,0.212668,2024-01-31 00:35:07.293,0.161462
4,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0,7443845.0,0.069505,2023-12-22 19:37:42.077,0.099460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7564783,6187,2024-02-12 14:06:04.553,2024-02-22,66,NaN,C,18260.00,25.74,499.0,7564783.0,0.126331,2024-02-12 21:06:24.883,0.163068
9707,7670991,4229,2024-03-19 12:41:07.250,2024-04-01,72,NaN,A,14845.10,19.24,644.0,7670991.0,0.055343,2024-03-19 18:41:16.367,0.034021
9708,7721327,6605,2024-04-01 10:55:15.323,2024-04-24,72,13.0,B,23668.50,22.24,557.0,7721327.0,0.117213,2024-04-01 16:55:24.813,0.075132
9709,7827471,5171,2024-04-29 15:05:15.953,2024-05-29,72,7.0,D,30369.44,25.00,526.0,7827471.0,0.156908,2024-05-03 16:47:42.313,0.219028
9710,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0,7358901.0,0.179799,2023-12-19 17:12:23.133,0.244204

In [18]:
#Full merge completed next steps are drop unessecary rows, sort them to the correct bin of gens, and upload and push them to s3

In [40]:
df_fullmergenew.rename(columns={'dtmStampCreation_x' : 'dtmStampCreation'}, inplace=True)
df_fullmergenew.drop(columns='dtmStampCreation_y',inplace=True)
df_fullmergenew.drop(columns='intAccountKey', inplace=True)

In [41]:
df_fullmergenew

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score
0,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0,0.144020,0.229042
1,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0,0.164120,0.091615
2,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0,0.072356,0.111799
3,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0,0.212668,0.161462
4,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0,0.069505,0.099460
...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7564783,6187,2024-02-12 14:06:04.553,2024-02-22,66,NaN,C,18260.00,25.74,499.0,0.126331,0.163068
9707,7670991,4229,2024-03-19 12:41:07.250,2024-04-01,72,NaN,A,14845.10,19.24,644.0,0.055343,0.034021
9708,7721327,6605,2024-04-01 10:55:15.323,2024-04-24,72,13.0,B,23668.50,22.24,557.0,0.117213,0.075132
9709,7827471,5171,2024-04-29 15:05:15.953,2024-05-29,72,7.0,D,30369.44,25.00,526.0,0.156908,0.219028
9710,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0,0.179799,0.244204

In [42]:
df_fullmergenew['Gen'] = np.where(((df_fullmergenew['bigAccountId'] % 10 == 0) | (df_fullmergenew['bigAccountId'] % 10 == 5)) & (df_fullmergenew['dtmStampCreation'] >= '2024-04-15'), 'Gen12', 'Gen11')
df_fullmergenew

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
0,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0,0.144020,0.229042,Gen11
1,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0,0.164120,0.091615,Gen11
2,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0,0.072356,0.111799,Gen11
3,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0,0.212668,0.161462,Gen11
4,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0,0.069505,0.099460,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7564783,6187,2024-02-12 14:06:04.553,2024-02-22,66,NaN,C,18260.00,25.74,499.0,0.126331,0.163068,Gen11
9707,7670991,4229,2024-03-19 12:41:07.250,2024-04-01,72,NaN,A,14845.10,19.24,644.0,0.055343,0.034021,Gen11
9708,7721327,6605,2024-04-01 10:55:15.323,2024-04-24,72,13.0,B,23668.50,22.24,557.0,0.117213,0.075132,Gen11
9709,7827471,5171,2024-04-29 15:05:15.953,2024-05-29,72,7.0,D,30369.44,25.00,526.0,0.156908,0.219028,Gen11
9710,7358901,6317,2023-11-20 10:26:24.643,2024-01-04,72,7.0,D,28804.62,24.99,517.0,0.179799,0.244204,Gen11

In [43]:
df_check.head()

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7463119,3416,2024-01-02 10:50:16.100,2024-01-16,72,13.0,B,22692.05,20.49,479.0,0.074451,0.135543,Gen11
1,7537832,5654,2024-02-01 17:10:31.693,2024-02-06,66,7.0,A1,17809.00,18.74,569.0,-0.016412,0.013493,Gen11
2,7808778,4892,2024-04-20 15:59:20.183,2024-04-22,72,NaN,B,17565.50,24.67,471.0,0.111494,0.147749,Gen11
3,7445683,4993,2023-12-23 09:13:16.957,2024-01-04,72,NaN,B,18934.36,22.00,618.0,0.068107,0.104364,Gen11
4,7651391,4625,2024-03-11 17:43:57.173,2024-03-21,72,NaN,C,27291.41,23.25,533.0,0.144349,0.123361,Gen11

In [44]:
df_fullmergenew.head()

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
0,7724580,7301,2024-04-02 14:15:14.917,2024-05-09,72,NaN,C,19417.80,26.74,528.0,0.144020,0.229042,Gen11
1,7729737,6641,2024-04-04 15:43:10.363,2024-04-11,72,NaN,C,18974.02,25.00,556.0,0.164120,0.091615,Gen11
2,7892756,7925,2024-05-28 12:36:22.153,2024-06-03,72,NaN,A,16994.00,21.24,643.0,0.072356,0.111799,Gen11
3,7532311,5454,2024-01-30 17:34:58.387,2024-03-05,66,NaN,D,15490.86,29.24,475.0,0.212668,0.161462,Gen11
4,7443845,6498,2023-12-22 12:17:40.030,2024-01-11,66,13.0,B,17967.25,21.00,471.0,0.069505,0.099460,Gen11

In [45]:
df_checksort = df_check.sort_values(by=['bigAccountId', 'dtmStampCreation'], ascending=[True, False])
df_checksort

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
4655,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
9523,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
3417,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
2291,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
8293,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,7903851,6290,2024-06-01 12:46:04.383,2024-06-04,66,NaN,C,19169.12,25.00,635.0,0.152650,NaN,Gen11
7842,7903992,6523,2024-06-01 13:13:43.417,2024-06-03,72,NaN,B,23602.93,25.00,NaN,0.130059,NaN,Gen11
7122,7904071,6495,2024-06-01 13:26:54.557,2024-06-04,72,NaN,B,17009.04,23.53,531.0,0.112839,NaN,Gen11
2912,7905023,7207,2024-06-01 17:05:15.523,2024-06-04,72,NaN,B,20825.26,20.74,513.0,0.095982,NaN,Gen11
211,7905868,3171,2024-06-03 09:52:31.883,2024-06-04,69,NaN,D,11031.02,29.24,580.0,0.180401,NaN,Gen11

In [46]:
df_fullmergesort = df_fullmergenew.sort_values(by=['bigAccountId', 'dtmStampCreation'], ascending=[True, False])
df_fullmergesort

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
862,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.139011,Gen11
861,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.081153,0.102351,Gen11
881,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.006578,0.025141,Gen11
882,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.136053,0.226860,Gen11
1126,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.069061,0.066089,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9411,7903851,6290,2024-06-01 12:46:04.383,2024-06-04,66,NaN,C,19169.12,25.00,635.0,NaN,NaN,Gen11
9434,7903992,6523,2024-06-01 13:13:43.417,2024-06-03,72,NaN,B,23602.93,25.00,NaN,NaN,NaN,Gen11
9470,7904071,6495,2024-06-01 13:26:54.557,2024-06-04,72,NaN,B,17009.04,23.53,531.0,NaN,NaN,Gen11
9471,7905023,7207,2024-06-01 17:05:15.523,2024-06-04,72,NaN,B,20825.26,20.74,513.0,NaN,NaN,Gen11
9472,7905868,3171,2024-06-03 09:52:31.883,2024-06-04,69,NaN,D,11031.02,29.24,580.0,NaN,NaN,Gen11

In [47]:
df_checksort = df_checksort.rename(columns={'Gen 11' : 'Gen 11 Score', 'Gen 12' : 'Gen 12 Score'})

df_checksort

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
4655,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
9523,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
3417,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
2291,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
8293,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,7903851,6290,2024-06-01 12:46:04.383,2024-06-04,66,NaN,C,19169.12,25.00,635.0,0.152650,NaN,Gen11
7842,7903992,6523,2024-06-01 13:13:43.417,2024-06-03,72,NaN,B,23602.93,25.00,NaN,0.130059,NaN,Gen11
7122,7904071,6495,2024-06-01 13:26:54.557,2024-06-04,72,NaN,B,17009.04,23.53,531.0,0.112839,NaN,Gen11
2912,7905023,7207,2024-06-01 17:05:15.523,2024-06-04,72,NaN,B,20825.26,20.74,513.0,0.095982,NaN,Gen11
211,7905868,3171,2024-06-03 09:52:31.883,2024-06-04,69,NaN,D,11031.02,29.24,580.0,0.180401,NaN,Gen11

In [48]:
df_checksort = df_checksort.reset_index(drop=True)
df_fullmergesort = df_fullmergesort.reset_index(drop=True)
df_checksort

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7903851,6290,2024-06-01 12:46:04.383,2024-06-04,66,NaN,C,19169.12,25.00,635.0,0.152650,NaN,Gen11
9707,7903992,6523,2024-06-01 13:13:43.417,2024-06-03,72,NaN,B,23602.93,25.00,NaN,0.130059,NaN,Gen11
9708,7904071,6495,2024-06-01 13:26:54.557,2024-06-04,72,NaN,B,17009.04,23.53,531.0,0.112839,NaN,Gen11
9709,7905023,7207,2024-06-01 17:05:15.523,2024-06-04,72,NaN,B,20825.26,20.74,513.0,0.095982,NaN,Gen11
9710,7905868,3171,2024-06-03 09:52:31.883,2024-06-04,69,NaN,D,11031.02,29.24,580.0,0.180401,NaN,Gen11

In [49]:
df_fullmergesort

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11 Score,Gen 12 Score,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.139011,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.081153,0.102351,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.006578,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.136053,0.226860,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.069061,0.066089,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706,7903851,6290,2024-06-01 12:46:04.383,2024-06-04,66,NaN,C,19169.12,25.00,635.0,NaN,NaN,Gen11
9707,7903992,6523,2024-06-01 13:13:43.417,2024-06-03,72,NaN,B,23602.93,25.00,NaN,NaN,NaN,Gen11
9708,7904071,6495,2024-06-01 13:26:54.557,2024-06-04,72,NaN,B,17009.04,23.53,531.0,NaN,NaN,Gen11
9709,7905023,7207,2024-06-01 17:05:15.523,2024-06-04,72,NaN,B,20825.26,20.74,513.0,NaN,NaN,Gen11
9710,7905868,3171,2024-06-03 09:52:31.883,2024-06-04,69,NaN,D,11031.02,29.24,580.0,NaN,NaN,Gen11

In [29]:
#indexes have been reset, now just write code that checks each row and shows where differences in it lie.

In [30]:
for row in range(df_checksort.shape[0]):
    for col in df_checksort:
        if df_checksort.at[row,col] != df_fullmergesort.at[row,col]:
            print(f"Difference found at row {row}, column {col}: df_checksort has {df_checksort.at[row,col]}, df_fullmergesort has {df_fullmergesort.at[row,col]}")

Difference found at row 0, column Gen 12 Score: df_checksort has 0.126122, df_fullmergesort has 0.139011
Difference found at row 1, column Gen 11 Score: df_checksort has 0.139163, df_fullmergesort has 0.081153
Difference found at row 1, column Gen 12 Score: df_checksort has 0.311783, df_fullmergesort has 0.102351
Difference found at row 2, column Gen 11 Score: df_checksort has 0.009565, df_fullmergesort has 0.006578
Difference found at row 3, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 3, column Gen 11 Score: df_checksort has 0.120231, df_fullmergesort has 0.136053
Difference found at row 3, column Gen 12 Score: df_checksort has 0.241734, df_fullmergesort has 0.22686
Difference found at row 4, column Gen 11 Score: df_checksort has 0.040068, df_fullmergesort has 0.069061
Difference found at row 4, column Gen 12 Score: df_checksort has 0.029945, df_fullmergesort has 0.066089
Difference found at row 5, column Gen 11 Score: df_checksort has 0.06764, df_fullmergesort has 0.068114
Difference found at row 5, column Gen 12 Score: df_checksort has 0.169795, df_fullmergesort has 0.145337
Difference found at row 6, column Gen 11 Score: df_checksort has 0.100966, df_fullmergesort has 0.073703
Difference found at row 6, column Gen 12 Score: df_checksort has 0.196215, df_fullmergesort has 0.113931
Difference found at row 7, column Gen 12 Score: df_checksort has 0.027252, df_fullmergesort has 0.024434
Difference found at row 8, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 8, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 8, column Gen 11 Score: df_checksort has 0.103118, df_fullmergesort has 0.113338
Difference found at row 8, column Gen 12 Score: df_checksort has 0.088937, df_fullmergesort has 0.069874
Difference found at row 9, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 9, column Gen 11 Score: df_checksort has 0.181053, df_fullmergesort has 0.160158
Difference found at row 9, column Gen 12 Score: df_checksort has 0.326166, df_fullmergesort has 0.181904
Difference found at row 10, column Gen 11 Score: df_checksort has 0.075556, df_fullmergesort has 0.083412
Difference found at row 10, column Gen 12 Score: df_checksort has 0.182296, df_fullmergesort has 0.213389
Difference found at row 11, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 11, column Gen 11 Score: df_checksort has 0.051827, df_fullmergesort has 0.107094
Difference found at row 11, column Gen 12 Score: df_checksort has 0.160317, df_fullmergesort has 0.177005
Difference found at row 12, column Gen 12 Score: df_checksort has 0.334915, df_fullmergesort has 0.317919
Difference found at row 13, column Gen 11 Score: df_checksort has 0.009599, df_fullmergesort has 0.009616
Difference found at row 13, column Gen 12 Score: df_checksort has 0.020261, df_fullmergesort has 0.020412
Difference found at row 14, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 14, column Gen 12 Score: df_checksort has 0.13298, df_fullmergesort has 0.29713
Difference found at row 15, column Gen 11 Score: df_checksort has 0.122273, df_fullmergesort has 0.111373
Difference found at row 15, column Gen 12 Score: df_checksort has 0.2019, df_fullmergesort has 0.165025
Difference found at row 16, column Gen 11 Score: df_checksort has 0.047385, df_fullmergesort has 0.052063
Difference found at row 16, column Gen 12 Score: df_checksort has 0.081562, df_fullmergesort has 0.116495
Difference found at row 17, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 17, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 17, column Gen 12 Score: df_checksort has 0.227542, df_fullmergesort has 0.247101
Difference found at row 18, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 18, column Gen 11 Score: df_checksort has 0.080863, df_fullmergesort has 0.0683
Difference found at row 18, column Gen 12 Score: df_checksort has 0.074019, df_fullmergesort has 0.040564
Difference found at row 19, column Gen 11 Score: df_checksort has 0.142172, df_fullmergesort has 0.124561
Difference found at row 19, column Gen 12 Score: df_checksort has 0.147048, df_fullmergesort has 0.111813
Difference found at row 20, column Gen 11 Score: df_checksort has -0.005514, df_fullmergesort has -0.005602
Difference found at row 20, column Gen 12 Score: df_checksort has 0.00902, df_fullmergesort has 0.006676
Difference found at row 21, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 21, column Gen 12 Score: df_checksort has 0.187109, df_fullmergesort has 0.233591
Difference found at row 22, column Gen 11 Score: df_checksort has 0.023445, df_fullmergesort has 0.01809
Difference found at row 22, column Gen 12 Score: df_checksort has 0.048837, df_fullmergesort has 0.025209
Difference found at row 23, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 23, column Gen 12 Score: df_checksort has 0.189752, df_fullmergesort has 0.143882
Difference found at row 24, column Gen 11 Score: df_checksort has 0.049379, df_fullmergesort has 0.033097
Difference found at row 24, column Gen 12 Score: df_checksort has 0.147995, df_fullmergesort has 0.082921
Difference found at row 25, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 25, column Gen 11 Score: df_checksort has 0.183325, df_fullmergesort has 0.160054
Difference found at row 25, column Gen 12 Score: df_checksort has 0.148616, df_fullmergesort has 0.171299
Difference found at row 26, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 27, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 27, column Gen 12 Score: df_checksort has 0.303334, df_fullmergesort has 0.279985
Difference found at row 28, column Gen 11 Score: df_checksort has -0.00761, df_fullmergesort has 0.000628
Difference found at row 28, column Gen 12 Score: df_checksort has 0.009908, df_fullmergesort has 0.010619
Difference found at row 29, column Gen 11 Score: df_checksort has 0.052283, df_fullmergesort has 0.053811
Difference found at row 29, column Gen 12 Score: df_checksort has 0.053155, df_fullmergesort has 0.060995
Difference found at row 30, column Gen 11 Score: df_checksort has 0.060643, df_fullmergesort has 0.057622
Difference found at row 30, column Gen 12 Score: df_checksort has 0.074025, df_fullmergesort has 0.07233
Difference found at row 31, column Gen 11 Score: df_checksort has 0.127252, df_fullmergesort has 0.114179
Difference found at row 31, column Gen 12 Score: df_checksort has 0.297083, df_fullmergesort has 0.277102
Difference found at row 32, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 32, column Gen 11 Score: df_checksort has 0.120514, df_fullmergesort has 0.14708
Difference found at row 32, column Gen 12 Score: df_checksort has 0.118174, df_fullmergesort has 0.11074
Difference found at row 33, column Gen 12 Score: df_checksort has 0.096961, df_fullmergesort has 0.100777
Difference found at row 34, column Gen 11 Score: df_checksort has -0.00482, df_fullmergesort has -0.002426
Difference found at row 34, column Gen 12 Score: df_checksort has 0.033581, df_fullmergesort has 0.045475
Difference found at row 35, column Gen 11 Score: df_checksort has 0.029449, df_fullmergesort has 0.057891
Difference found at row 35, column Gen 12 Score: df_checksort has 0.117114, df_fullmergesort has 0.070609
Difference found at row 36, column Gen 11 Score: df_checksort has 0.082838, df_fullmergesort has 0.117627
Difference found at row 36, column Gen 12 Score: df_checksort has 0.21209, df_fullmergesort has 0.243624
Difference found at row 37, column Gen 11 Score: df_checksort has 0.002109, df_fullmergesort has -0.003215
Difference found at row 37, column Gen 12 Score: df_checksort has 0.045026, df_fullmergesort has 0.033636
Difference found at row 38, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 38, column Gen 11 Score: df_checksort has 0.134685, df_fullmergesort has 0.077092
Difference found at row 39, column Gen 11 Score: df_checksort has 0.019929, df_fullmergesort has 0.020527
Difference found at row 39, column Gen 12 Score: df_checksort has 0.043045, df_fullmergesort has 0.022146
Difference found at row 40, column Gen 12 Score: df_checksort has 0.269108, df_fullmergesort has 0.244204
Difference found at row 41, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 41, column Gen 11 Score: df_checksort has 0.0968, df_fullmergesort has 0.084056
Difference found at row 41, column Gen 12 Score: df_checksort has 0.223564, df_fullmergesort has 0.239968
Difference found at row 44, column Gen 12 Score: df_checksort has 0.126881, df_fullmergesort has 0.131252
Difference found at row 45, column Gen 11 Score: df_checksort has 0.092587, df_fullmergesort has 0.092472
Difference found at row 45, column Gen 12 Score: df_checksort has 0.277672, df_fullmergesort has 0.233064
Difference found at row 46, column Gen 11 Score: df_checksort has 0.094832, df_fullmergesort has 0.173679
Difference found at row 46, column Gen 12 Score: df_checksort has 0.121032, df_fullmergesort has 0.122474
Difference found at row 47, column Gen 12 Score: df_checksort has 0.112738, df_fullmergesort has 0.113065
Difference found at row 48, column Gen 12 Score: df_checksort has 0.032805, df_fullmergesort has 0.031103
Difference found at row 49, column Gen 12 Score: df_checksort has 0.006144, df_fullmergesort has 0.107807
Difference found at row 50, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 50, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 50, column Gen 11 Score: df_checksort has 0.097509, df_fullmergesort has 0.124875
Difference found at row 50, column Gen 12 Score: df_checksort has 0.146122, df_fullmergesort has 0.130368
Difference found at row 51, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 51, column Gen 11 Score: df_checksort has 0.101375, df_fullmergesort has 0.099234
Difference found at row 51, column Gen 12 Score: df_checksort has 0.128788, df_fullmergesort has 0.121519
Difference found at row 52, column Gen 11 Score: df_checksort has 0.145001, df_fullmergesort has 0.101787
Difference found at row 52, column Gen 12 Score: df_checksort has 0.269561, df_fullmergesort has 0.142982
Difference found at row 53, column Gen 11 Score: df_checksort has 0.053207, df_fullmergesort has 0.050247
Difference found at row 53, column Gen 12 Score: df_checksort has 0.202399, df_fullmergesort has 0.135588
Difference found at row 54, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 54, column Gen 11 Score: df_checksort has 0.191118, df_fullmergesort has 0.188932
Difference found at row 54, column Gen 12 Score: df_checksort has 0.214631, df_fullmergesort has 0.255378
Difference found at row 55, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 55, column Gen 11 Score: df_checksort has 0.200641, df_fullmergesort has 0.194537
Difference found at row 55, column Gen 12 Score: df_checksort has 0.176924, df_fullmergesort has 0.158089
Difference found at row 56, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 56, column Gen 11 Score: df_checksort has 0.051101, df_fullmergesort has 0.060376
Difference found at row 57, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 57, column Gen 11 Score: df_checksort has 0.115807, df_fullmergesort has 0.193072
Difference found at row 57, column Gen 12 Score: df_checksort has 0.179524, df_fullmergesort has 0.13094
Difference found at row 58, column Gen 11 Score: df_checksort has -0.017731, df_fullmergesort has -0.009605
Difference found at row 58, column Gen 12 Score: df_checksort has 0.053676, df_fullmergesort has 0.044032
Difference found at row 59, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 59, column Gen 11 Score: df_checksort has 0.107368, df_fullmergesort has 0.101815
Difference found at row 59, column Gen 12 Score: df_checksort has 0.166036, df_fullmergesort has 0.184979
Difference found at row 60, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 60, column Gen 11 Score: df_checksort has 0.120047, df_fullmergesort has 0.136987
Difference found at row 60, column Gen 12 Score: df_checksort has 0.116474, df_fullmergesort has 0.160966
Difference found at row 61, column Gen 11 Score: df_checksort has 0.056014, df_fullmergesort has 0.048223
Difference found at row 61, column Gen 12 Score: df_checksort has 0.104695, df_fullmergesort has 0.051663
Difference found at row 62, column Gen 11 Score: df_checksort has -0.022315, df_fullmergesort has -0.022181
Difference found at row 62, column Gen 12 Score: df_checksort has 0.011793, df_fullmergesort has 0.029272
Difference found at row 63, column Gen 12 Score: df_checksort has 0.161311, df_fullmergesort has 0.166855
Difference found at row 64, column Gen 11 Score: df_checksort has -0.010682, df_fullmergesort has -0.004771
Difference found at row 64, column Gen 12 Score: df_checksort has 0.018471, df_fullmergesort has 0.024601
Difference found at row 65, column Gen 11 Score: df_checksort has 0.037522, df_fullmergesort has 0.046047
Difference found at row 65, column Gen 12 Score: df_checksort has 0.053088, df_fullmergesort has 0.053172
Difference found at row 66, column Gen 12 Score: df_checksort has 0.027692, df_fullmergesort has 0.04967
Difference found at row 67, column Gen 11 Score: df_checksort has 0.02596, df_fullmergesort has 0.025966
Difference found at row 67, column Gen 12 Score: df_checksort has 0.06087, df_fullmergesort has 0.124659
Difference found at row 68, column Gen 11 Score: df_checksort has 0.029495, df_fullmergesort has 0.034831
Difference found at row 68, column Gen 12 Score: df_checksort has 0.048281, df_fullmergesort has 0.04224
Difference found at row 69, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 69, column Gen 11 Score: df_checksort has 0.031023, df_fullmergesort has 0.032144
Difference found at row 69, column Gen 12 Score: df_checksort has 0.095317, df_fullmergesort has 0.071195
Difference found at row 70, column Gen 11 Score: df_checksort has 0.009662, df_fullmergesort has 0.010175
Difference found at row 70, column Gen 12 Score: df_checksort has 0.112347, df_fullmergesort has 0.123481
Difference found at row 71, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 71, column Gen 12 Score: df_checksort has 0.114782, df_fullmergesort has 0.165422
Difference found at row 72, column Gen 11 Score: df_checksort has 0.001188, df_fullmergesort has 0.002494
Difference found at row 72, column Gen 12 Score: df_checksort has 0.015726, df_fullmergesort has 0.024968
Difference found at row 73, column Gen 11 Score: df_checksort has 0.026706, df_fullmergesort has 0.023503
Difference found at row 73, column Gen 12 Score: df_checksort has 0.10991, df_fullmergesort has 0.104781
Difference found at row 74, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 74, column Gen 12 Score: df_checksort has 0.281401, df_fullmergesort has 0.181294
Difference found at row 75, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 75, column Gen 11 Score: df_checksort has 0.130941, df_fullmergesort has 0.130439
Difference found at row 75, column Gen 12 Score: df_checksort has 0.236615, df_fullmergesort has 0.121685
Difference found at row 76, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 76, column Gen 12 Score: df_checksort has 0.130261, df_fullmergesort has 0.14551
Difference found at row 77, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 77, column Gen 11 Score: df_checksort has 0.178526, df_fullmergesort has 0.162436
Difference found at row 77, column Gen 12 Score: df_checksort has 0.207841, df_fullmergesort has 0.25642
Difference found at row 78, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 78, column Gen 11 Score: df_checksort has 0.011075, df_fullmergesort has 0.006485
Difference found at row 78, column Gen 12 Score: df_checksort has 0.039355, df_fullmergesort has 0.146661
Difference found at row 79, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 79, column Gen 12 Score: df_checksort has 0.152274, df_fullmergesort has 0.217203
Difference found at row 80, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 80, column Gen 12 Score: df_checksort has 0.1177, df_fullmergesort has 0.111123
Difference found at row 81, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 81, column Gen 11 Score: df_checksort has 0.095957, df_fullmergesort has 0.113333
Difference found at row 81, column Gen 12 Score: df_checksort has 0.110487, df_fullmergesort has 0.145514
Difference found at row 82, column Gen 11 Score: df_checksort has 0.017021, df_fullmergesort has 0.01343
Difference found at row 82, column Gen 12 Score: df_checksort has 0.089586, df_fullmergesort has 0.040245
Difference found at row 83, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 83, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 83, column Gen 11 Score: df_checksort has 0.075342, df_fullmergesort has 0.07024
Difference found at row 83, column Gen 12 Score: df_checksort has 0.072703, df_fullmergesort has 0.097495
Difference found at row 84, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 84, column Gen 11 Score: df_checksort has 0.06804, df_fullmergesort has 0.06484
Difference found at row 84, column Gen 12 Score: df_checksort has 0.08408, df_fullmergesort has 0.122724
Difference found at row 85, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 85, column Gen 12 Score: df_checksort has 0.042724, df_fullmergesort has 0.082061
Difference found at row 86, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 86, column Gen 11 Score: df_checksort has 0.092344, df_fullmergesort has 0.155789
Difference found at row 86, column Gen 12 Score: df_checksort has 0.136589, df_fullmergesort has 0.171105
Difference found at row 87, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 87, column Gen 12 Score: df_checksort has 0.08196, df_fullmergesort has 0.098134
Difference found at row 88, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 88, column MaxFico: df_checksort has nan, df_fullmergesort has nan
Difference found at row 88, column Gen 12 Score: df_checksort has 0.149584, df_fullmergesort has 0.149325
Difference found at row 89, column Gen 11 Score: df_checksort has 0.070822, df_fullmergesort has 0.070893
Difference found at row 89, column Gen 12 Score: df_checksort has 0.050684, df_fullmergesort has 0.085579
Difference found at row 90, column intOpenBKType: df_checksort has nan, df_fullmergesort has nan
Difference found at row 90, column Gen 12 Score: df_checksort has 0.130224, df_fullmergesort has 0.132061

In [ ]:
df_fullmergesort