In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import pyodbc
import numpy as np
import pickle

## Functions

In [2]:
class GetData:
    def __init__(self):
        pass
    def read_sql_script(self, str_local_path):
        str_query = open(str_local_path, 'r').read()
        # save to object
        self.str_query = str_query
        # return object
        return self
    def pull_data_from_sql(self, conn, bool_close_conn=True):
        df = pd.read_sql_query(
            sql=self.str_query,
            con=conn,
        )
        if bool_close_conn:
            conn.close()
        else:
            pass
        return df

## Constants

In [3]:
str_project = os.getcwd().split('\\')[3]
print(f'Project: {str_project}')

str_task = os.getcwd().split('\\')[4]
print(f'Task: {str_task}')

str_subtask = os.getcwd().split('\\')[5]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 20240521_bridger_internship
Task: 03_python
Subtask: 01_jupyter_practice

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

## Read SQL

In [5]:
# initialize class To create df_check
cls_get_data = GetData()

#read query
str_filename = 'GenScoresTable2024Revamp.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_check = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df_check

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14312\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7912006,1880,2024-06-05 13:53:41.907,2024-06-07,72,NaN,B,18612.94,25.00,484.0,0.093875,0.137118,Gen11
9935,7912097,6641,2024-06-05 14:17:38.237,2024-06-07,66,NaN,B,21207.46,25.00,526.0,0.128636,0.459248,Gen11
9936,7912482,8519,2024-06-05 15:42:28.690,2024-06-07,72,NaN,C,18566.00,18.00,570.0,0.160182,0.528910,Gen11
9937,7913299,1671,2024-06-06 08:36:29.413,2024-06-07,72,NaN,D,15660.00,29.24,516.0,0.173808,0.349268,Gen11
9938,7914653,6988,2024-06-06 14:09:48.700,2024-06-07,72,NaN,B,35000.00,25.59,NaN,0.102383,0.716730,Gen11

## TempStaticPool & Account Query

In [6]:
# initialize class And gather data from tempstaticpool and account tables
cls_get_data = GetData()

#read query
str_filename = 'TblTempAndAcc.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftemp = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftemp

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14312\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico
0,7346914,1897,2023-11-15 10:50:56.573,2024-01-05,72,13.0,A1,29487.72,19.24,545.0
1,7350992,1567,2023-11-16 15:48:18.670,2024-01-08,72,13.0,A,22071.16,20.86,535.0
2,7353601,3416,2023-11-17 14:23:21.397,2024-01-03,72,13.0,A1,23298.17,19.74,540.0
3,7358046,1092,2023-11-19 09:28:43.840,2024-01-30,72,NaN,B,23398.94,24.00,624.0
4,7367420,920,2023-11-24 12:21:02.140,2024-01-22,72,13.0,A1,16068.94,17.24,642.0
...,...,...,...,...,...,...,...,...,...,...
9934,7908440,3814,2024-06-04 09:06:58.203,2024-06-04,72,7.0,A1,26924.58,20.33,631.0
9935,7908853,7334,2024-06-04 10:54:05.147,2024-06-05,72,NaN,D,28429.72,29.24,558.0
9936,7909092,7301,2024-06-04 11:51:56.883,2024-06-06,72,7.0,C,15885.00,26.74,508.0
9937,7910657,6476,2024-06-05 07:27:50.560,2024-06-06,66,NaN,C,19373.24,25.00,558.0
9938,7910984,7301,2024-06-05 09:53:06.977,2024-06-06,72,7.0,C,23377.50,25.58,574.0

## DimScoreCard Gen11 Query

In [7]:
# initialize class and gather data from the dimscorecard table
cls_get_data = GetData()

#read query
str_filename = 'DimScoreCardGen11.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dfgen11 = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dfgen11

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14312\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,intAccountKey,fltDebtorScore,dtmStampCreation,strScoreCardVersion
0,5781417,0.246906,2021-10-05 01:46:55.963,genxi
1,5784534,0.205792,2021-10-05 01:53:12.897,genxi
2,5784536,0.638507,2021-10-05 01:53:15.070,genxi
3,5784541,0.401850,2021-10-05 01:53:16.780,genxi
4,5784535,0.170895,2021-10-05 01:53:21.480,genxi
...,...,...,...,...
3610332,5794304,0.218602,2021-10-14 21:13:01.727,genxi
3610333,5794579,0.302435,2021-10-14 21:13:26.360,genxi
3610334,5785306,0.209544,2021-10-14 21:13:31.873,genxi
3610335,5794581,0.385677,2021-10-14 21:15:12.637,genxi
3610336,5780743,0.013605,2021-10-14 21:15:35.867,genxi

In [8]:
# sort dataframe by accountkey and dtmstampcreation
dfgen11 = dfgen11.sort_values(by=['intAccountKey','dtmStampCreation'], ascending=[True,False])

In [9]:
# apply row numbers to all of the most recent values based on account
dfgen11['rownum'] = dfgen11.groupby('intAccountKey').cumcount() + 1

In [10]:
# create new datafram with only row 1 values
dfgen11sort = dfgen11[dfgen11['rownum']==1]

In [11]:
#drop row num values
dfgen11sort.drop(columns=['rownum'])

,intAccountKey,fltDebtorScore,dtmStampCreation,strScoreCardVersion
1762421,5658431,0.215984,2023-04-17 20:50:58.223,genxi_v2
6104,5677429,0.238938,2021-10-22 17:33:27.137,genxi
1034980,5695506,0.316659,2022-10-13 15:11:39.897,genxi_v2
148915,5698957,0.276173,2022-01-04 17:52:46.010,genxi
1044949,5700901,0.164306,2022-10-13 22:16:22.463,genxi_v2
...,...,...,...,...
3571448,7921911,0.098512,2024-06-10 02:05:29.067,genxi_v2_3
3571449,7921912,0.076506,2024-06-10 02:05:43.667,genxi_v2_3
3571450,7921913,0.327144,2024-06-10 02:20:33.187,genxi_v2_3
3571452,7921916,0.110652,2024-06-10 02:31:29.800,genxi_v2_3
3571455,7921919,0.112990,2024-06-10 02:50:51.567,genxi_v2_3

## DimScoreCard Gen12 Query

In [12]:
# initialize class and gather data from the dimscorecard table
cls_get_data = GetData()

#read query
str_filename = 'DimScoreCardGen12.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dfgen12 = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dfgen12

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14312\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,intAccountKey,fltDebtorScore,dtmStampCreation,strScoreCardVersion
0,7374552,0.267285,2023-11-27 21:45:48.020,genxii
1,7374548,0.118196,2023-11-27 21:45:49.403,genxii
2,7374553,0.178505,2023-11-27 21:45:52.257,genxii
3,7374550,0.168624,2023-11-27 21:46:00.767,genxii
4,7355170,0.165895,2023-11-27 21:46:06.750,genxii
...,...,...,...,...
819727,7726494,0.312879,2024-04-03 18:41:12.547,genxii_v2
819728,7725024,0.147269,2024-04-03 18:41:20.667,genxii_v2
819729,7714845,0.038469,2024-04-03 18:41:29.480,genxii_v2
819730,7723609,0.164602,2024-04-03 18:41:30.977,genxii_v2
819731,7726493,0.166063,2024-04-03 18:41:32.247,genxii_v2

In [13]:
# sort dataframe by accountkey and dtmstampcreation
dfgen12 = dfgen12.sort_values(by=['intAccountKey','dtmStampCreation'], ascending=[True,False])

In [14]:
# apply row numbers to all of the most recent values based on account
dfgen12['rownum'] = dfgen12.groupby('intAccountKey').cumcount() + 1

In [15]:
# create new datafram with only row 1 values
dfgen12sort = dfgen12[dfgen12['rownum']==1]

In [16]:
#drop row num values
dfgen12sort.drop(columns=['rownum'])

,intAccountKey,fltDebtorScore,dtmStampCreation,strScoreCardVersion
74469,5895917,0.296115,2023-12-19 16:16:55.547,genxii
332663,6187153,0.165202,2024-03-04 22:33:21.370,genxii
287297,6202801,0.060866,2023-12-22 19:53:51.847,genxii
400311,6342021,0.042656,2024-02-15 17:46:29.933,genxii
254265,6402651,0.210184,2024-01-04 21:32:51.847,genxii
...,...,...,...,...
774810,7921911,0.657719,2024-06-10 02:05:31.060,genxii_v3
774811,7921912,0.531362,2024-06-10 02:05:45.383,genxii_v3
774812,7921913,0.517948,2024-06-10 02:20:34.843,genxii_v3
774814,7921916,0.059035,2024-06-10 02:31:31.440,genxii_v3
774817,7921919,0.101888,2024-06-10 02:50:53.500,genxii_v3

## Join Gen11 and Gen12 Tables

In [17]:
# merge gen tables on account key
dfgentable = pd.merge(dfgen11sort, dfgen12sort, left_on='intAccountKey', right_on=['intAccountKey'], how='inner')
dfgentable

,intAccountKey,fltDebtorScore_x,dtmStampCreation_x,strScoreCardVersion_x,rownum_x,fltDebtorScore_y,dtmStampCreation_y,strScoreCardVersion_y,rownum_y
0,5895917,0.138294,2023-12-19 16:16:52.077,genxi_v2,1,0.296115,2023-12-19 16:16:55.547,genxii,1
1,6187153,0.086811,2024-03-04 22:33:20.040,genxi_v2,1,0.165202,2024-03-04 22:33:21.370,genxii,1
2,6202801,0.098147,2023-12-22 19:53:50.027,genxi_v2,1,0.060866,2023-12-22 19:53:51.847,genxii,1
3,6342021,0.044797,2024-02-15 17:46:28.270,genxi_v2,1,0.042656,2024-02-15 17:46:29.933,genxii,1
4,6402651,0.271056,2024-01-04 21:32:44.110,genxi_v2_2,1,0.210184,2024-01-04 21:32:51.847,genxii,1
...,...,...,...,...,...,...,...,...,...
342269,7921911,0.098512,2024-06-10 02:05:29.067,genxi_v2_3,1,0.657719,2024-06-10 02:05:31.060,genxii_v3,1
342270,7921912,0.076506,2024-06-10 02:05:43.667,genxi_v2_3,1,0.531362,2024-06-10 02:05:45.383,genxii_v3,1
342271,7921913,0.327144,2024-06-10 02:20:33.187,genxi_v2_3,1,0.517948,2024-06-10 02:20:34.843,genxii_v3,1
342272,7921916,0.110652,2024-06-10 02:31:29.800,genxi_v2_3,1,0.059035,2024-06-10 02:31:31.440,genxii_v3,1
342273,7921919,0.112990,2024-06-10 02:50:51.567,genxi_v2_3,1,0.101888,2024-06-10 02:50:53.500,genxii_v3,1

## Join GenTable and AccountTable

In [18]:
# merge gen table and tempstaticpool table
dffullmerge = pd.merge(dftemp, dfgentable, left_on='bigAccountId', right_on='intAccountKey', how='left')
dffullmerge

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,intAccountKey,fltDebtorScore_x,dtmStampCreation_x,strScoreCardVersion_x,rownum_x,fltDebtorScore_y,dtmStampCreation_y,strScoreCardVersion_y,rownum_y
0,7346914,1897,2023-11-15 10:50:56.573,2024-01-05,72,13.0,A1,29487.72,19.24,545.0,7346914.0,-0.007610,2024-01-05 19:19:17.347,genxi_v2_2,1.0,0.009908,2024-01-05 19:19:19.490,genxii,1.0
1,7350992,1567,2023-11-16 15:48:18.670,2024-01-08,72,13.0,A,22071.16,20.86,535.0,7350992.0,0.060643,2024-01-08 22:22:13.493,genxi_v2_2,1.0,0.074025,2024-01-08 22:22:16.173,genxii,1.0
2,7353601,3416,2023-11-17 14:23:21.397,2024-01-03,72,13.0,A1,23298.17,19.74,540.0,7353601.0,-0.004820,2024-01-03 23:41:02.147,genxi_v2_2,1.0,0.033581,2024-01-03 23:41:03.717,genxii,1.0
3,7358046,1092,2023-11-19 09:28:43.840,2024-01-30,72,NaN,B,23398.94,24.00,624.0,7358046.0,0.134685,2024-01-30 23:26:55.667,genxi_v2_2,1.0,0.130166,2024-01-30 23:26:59.007,genxii,1.0
4,7367420,920,2023-11-24 12:21:02.140,2024-01-22,72,13.0,A1,16068.94,17.24,642.0,7367420.0,-0.024979,2024-01-22 17:02:29.297,genxi_v2_2,1.0,0.006144,2024-01-22 17:02:31.177,genxii,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7908440,3814,2024-06-04 09:06:58.203,2024-06-04,72,7.0,A1,26924.58,20.33,631.0,7908440.0,0.084309,2024-06-04 22:47:41.987,genxi_v2_3,1.0,0.054127,2024-06-04 22:47:36.990,genxii_v3,1.0
9935,7908853,7334,2024-06-04 10:54:05.147,2024-06-05,72,NaN,D,28429.72,29.24,558.0,7908853.0,0.183968,2024-06-05 21:51:41.700,genxi_v2_3,1.0,0.438860,2024-06-05 21:51:44.417,genxii_v3,1.0
9936,7909092,7301,2024-06-04 11:51:56.883,2024-06-06,72,7.0,C,15885.00,26.74,508.0,7909092.0,0.141705,2024-06-06 17:57:25.433,genxi_v2_3,1.0,0.567571,2024-06-06 17:57:27.993,genxii_v3,1.0
9937,7910657,6476,2024-06-05 07:27:50.560,2024-06-06,66,NaN,C,19373.24,25.00,558.0,7910657.0,0.155856,2024-06-06 22:47:31.983,genxi_v2_3,1.0,0.197112,2024-06-06 22:47:33.567,genxii_v3,1.0
9938,7910984,7301,2024-06-05 09:53:06.977,2024-06-06,72,7.0,C,23377.50,25.58,574.0,7910984.0,0.145653,2024-06-06 22:53:22.877,genxi_v2_3,1.0,0.496919,2024-06-06 22:53:25.910,genxii_v3,1.0

In [19]:
# drop unneeded columns
dffullmerge.drop(columns='intAccountKey', inplace=True)
dffullmerge.drop(columns='dtmStampCreation_x', inplace=True)
dffullmerge.drop(columns='strScoreCardVersion_x', inplace=True)
dffullmerge.drop(columns='rownum_x', inplace=True)
dffullmerge.drop(columns='dtmStampCreation_y', inplace=True)
dffullmerge.drop(columns='strScoreCardVersion_y', inplace=True)
dffullmerge.drop(columns='rownum_y', inplace=True)
dffullmerge

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,fltDebtorScore_x,fltDebtorScore_y
0,7346914,1897,2023-11-15 10:50:56.573,2024-01-05,72,13.0,A1,29487.72,19.24,545.0,-0.007610,0.009908
1,7350992,1567,2023-11-16 15:48:18.670,2024-01-08,72,13.0,A,22071.16,20.86,535.0,0.060643,0.074025
2,7353601,3416,2023-11-17 14:23:21.397,2024-01-03,72,13.0,A1,23298.17,19.74,540.0,-0.004820,0.033581
3,7358046,1092,2023-11-19 09:28:43.840,2024-01-30,72,NaN,B,23398.94,24.00,624.0,0.134685,0.130166
4,7367420,920,2023-11-24 12:21:02.140,2024-01-22,72,13.0,A1,16068.94,17.24,642.0,-0.024979,0.006144
...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7908440,3814,2024-06-04 09:06:58.203,2024-06-04,72,7.0,A1,26924.58,20.33,631.0,0.084309,0.054127
9935,7908853,7334,2024-06-04 10:54:05.147,2024-06-05,72,NaN,D,28429.72,29.24,558.0,0.183968,0.438860
9936,7909092,7301,2024-06-04 11:51:56.883,2024-06-06,72,7.0,C,15885.00,26.74,508.0,0.141705,0.567571
9937,7910657,6476,2024-06-05 07:27:50.560,2024-06-06,66,NaN,C,19373.24,25.00,558.0,0.155856,0.197112
9938,7910984,7301,2024-06-05 09:53:06.977,2024-06-06,72,7.0,C,23377.50,25.58,574.0,0.145653,0.496919

In [20]:
# rename Debtor Scores columns to gen 11 and 12
dffullmerge.rename(columns={'fltDebtorScore_x' : 'Gen 11'}, inplace=True)
dffullmerge.rename(columns={'fltDebtorScore_y' : 'Gen 12'}, inplace=True)

In [21]:
# creates extra column to pick gen version used
dffullmerge['Gen'] = np.where(((dffullmerge['bigAccountId'] % 10 == 0) | (dffullmerge['bigAccountId'] % 10 == 5)) & (dffullmerge['dtmStampCreation'] >= '2024-04-15'), 'Gen12', 'Gen11')
dffullmerge

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7346914,1897,2023-11-15 10:50:56.573,2024-01-05,72,13.0,A1,29487.72,19.24,545.0,-0.007610,0.009908,Gen11
1,7350992,1567,2023-11-16 15:48:18.670,2024-01-08,72,13.0,A,22071.16,20.86,535.0,0.060643,0.074025,Gen11
2,7353601,3416,2023-11-17 14:23:21.397,2024-01-03,72,13.0,A1,23298.17,19.74,540.0,-0.004820,0.033581,Gen11
3,7358046,1092,2023-11-19 09:28:43.840,2024-01-30,72,NaN,B,23398.94,24.00,624.0,0.134685,0.130166,Gen11
4,7367420,920,2023-11-24 12:21:02.140,2024-01-22,72,13.0,A1,16068.94,17.24,642.0,-0.024979,0.006144,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7908440,3814,2024-06-04 09:06:58.203,2024-06-04,72,7.0,A1,26924.58,20.33,631.0,0.084309,0.054127,Gen12
9935,7908853,7334,2024-06-04 10:54:05.147,2024-06-05,72,NaN,D,28429.72,29.24,558.0,0.183968,0.438860,Gen11
9936,7909092,7301,2024-06-04 11:51:56.883,2024-06-06,72,7.0,C,15885.00,26.74,508.0,0.141705,0.567571,Gen11
9937,7910657,6476,2024-06-05 07:27:50.560,2024-06-06,66,NaN,C,19373.24,25.00,558.0,0.155856,0.197112,Gen11
9938,7910984,7301,2024-06-05 09:53:06.977,2024-06-06,72,7.0,C,23377.50,25.58,574.0,0.145653,0.496919,Gen11

In [22]:
# reset index and sort for both df_check and dffullmerge for future comparison
df_check = df_check.sort_values(by=['bigAccountId','dtmStampCreation'], ascending=[True,False])
df_check = df_check.reset_index(drop=True)
dffullmerge = dffullmerge.sort_values(by=['bigAccountId','dtmStampCreation'],ascending=[True,False])
dffullmerge = dffullmerge.reset_index(drop=True)

In [23]:
# qucik check on dataframes

In [24]:
df_check.head()

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11

In [25]:
dffullmerge.head()

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11

In [26]:
# searches both dataframes and looks for differences
count = 0
for row in range(df_check.shape[0]):
    for col in df_check.columns:
        val1 = df_check.at[row,col]
        val2 = dffullmerge.at[row,col]
        if val1 != val2 and not (pd.isna(val1) and pd.isna(val2)):
            print(f"Difference found at row {row}, column {col}: df_check has {df_check.at[row,col]}, dffullmerge has {dffullmerge.at[row,col]}")
            count += 1

Difference found at row 422, column Gen 12: df_check has 0.022268, dffullmerge has nan
Difference found at row 439, column Gen 12: df_check has 0.047957, dffullmerge has nan
Difference found at row 1664, column Gen 12: df_check has 0.035129, dffullmerge has nan
Difference found at row 1840, column Gen 12: df_check has 0.109664, dffullmerge has nan
Difference found at row 2940, column Gen 12: df_check has 0.038615, dffullmerge has nan
Difference found at row 2983, column Gen 12: df_check has 0.131652, dffullmerge has nan
Difference found at row 3040, column Gen 12: df_check has 0.029554, dffullmerge has nan

In [27]:
print(f"There were a total of {count} differences found in the data")

There were a total of 7 differences found in the data

In [28]:
dffullmerge.loc[3040]

bigAccountId                               7520551
bigDealerId                                   6718
dtmStampCreation        2024-01-26 10:14:55.727000
dtmFunded                      2024-02-09 00:00:00
intTerm                                         72
intOpenBKType                                  NaN
strTier                                       Gold
AmtFinanced                               25738.19
OriginalInterestRate                         15.99
MaxFico                                      613.0
Gen 11                                         NaN
Gen 12                                         NaN
Gen                                          Gen11
Name: 3040, dtype: object

In [29]:
df_check.loc[3040]

bigAccountId                               7520551
bigDealerId                                   6718
dtmStampCreation        2024-01-26 10:14:55.727000
dtmFunded                      2024-02-09 00:00:00
intTerm                                         72
intOpenBKType                                  NaN
strTier                                       Gold
AmtFinanced                               25738.19
OriginalInterestRate                         15.99
MaxFico                                      613.0
Gen 11                                         NaN
Gen 12                                    0.029554
Gen                                          Gen11
Name: 3040, dtype: object