### Import libraries

In [1]:
import os
import pandas as pd
import pickle

try:
    from tqdm import tqdm
except ModuleNotFoundError:
    ! pip install tqdm
    from tqdm import tqdm

try:
    import matplotlib.pyplot as plt
except ModuleNotFoundError:
    ! pip install matplotlib
    import matplotlib.pyplot as plt

### Functions

In [2]:
def read_my_csv_file(str_local_path):
    print(f'Reading file from {str_local_path}...')
    df = pd.read_csv(str_local_path)
    return df

In [3]:
def tag_franchise(str_dealer_type):
    if str_dealer_type == 'Franchise':
        return 1
    else:
        return 0

In [4]:
def tag_dealer_type(str_dealer_type, str_target_dealer_type):
    if str_dealer_type == str_target_dealer_type:
        return 1
    else:
        return 0

In [5]:
class PlotProportions:
    def __init__(self):
        pass
    def create_proportion_table(self, df):
        # get nrows in df
        int_nrows = df.shape[0]
        # save to self
        self.int_nrows = int_nrows
        
        # get series
        ser_freq = df['DealerType'].value_counts(normalize=True)
        # convert series to df
        df_freq = ser_freq.reset_index()
        # rename the columns
        df_freq.columns = ['dealer_type', 'prop']
        # save the object to self
        self.df_freq = df_freq
        
        # return object
        return self
    def plot_proportions(self, str_local_path, bool_show_plot=True):
        # create
        fig, ax = plt.subplots(figsize=(9,5))
        # title
        ax.set_title(f'Proportion of Dealer Types (N = {self.int_nrows})')
        # x
        ax.set_xlabel('Dealer Type')
        # y
        ax.set_ylabel('Proportion')
        # plot
        bars = ax.bar(self.df_freq['dealer_type'], self.df_freq['prop'])
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:0.2f}',
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 3),  # 3 points vertical offset
                textcoords="offset points",
                ha='center',
                va='bottom',
            )

        # save to self
        self.fig = fig
        
        # save
        plt.savefig(
            str_local_path, 
            bbox_inches='tight',
        )
        
        # show
        if bool_show_plot:
            plt.show()
        else:
            pass

In [6]:
#simple use case for classes

In [7]:
class Student(object):
    #"initialize the attributes for an object"
    def __init__(self, name, age, gender, level, grades=None):
        self.name = name
        self.age = age
        self.gender = gender
        self.level = level
        self.grades = grades or {}
    # add grades to a dictionary
    def setGrade(self, course, grade):
        self.grades[course] = grade
    # call a course and output grade    
    def getGrade(self, course):
        return self.grades[course]
    # calculate gpa
    def getGPA(self):
        return sum(self.grades.values())/len(self.grades)
    
# Define students & grades
john = Student("John", 12, "male", 6, {"math":3.3, "science":3.7})
jane = Student("Jane", 12, "female", 6, {"math":3.5, "science":4.0})
# Use new methods
print(jane.getGPA())
print(john.getGrade("math"))
john.setGrade("history", 4.0)
print(john.getGPA())

3.75
3.3
3.6666666666666665

### Constants

In [30]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('/')[6]
print(f'Subtask: {str_subtask}')
str_dirname_output = './output'

Project: 20240509-christian-internship
Task: 03_python
Subtask: 01_jupyter_practice

### Make output directory

In [9]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

### Read csv file

In [10]:
%%time

str_filename = 'all_funded_loans.csv'
#str_local_path = f'../../02_sql/output/{str_filename}'
str_uri = f's3://{str_project}/02_sql/output/{str_filename}'
df = read_my_csv_file(
    #str_local_path,
    str_uri,
)
# show
df

Reading file from s3://20240509-christian-internship/02_sql/output/all_funded_loans.csv...

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:275: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)
/tmp/ipykernel_3654/389110400.py:3: DtypeWarning: Columns (4,7,26,115,127,150,201,203) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(str_local_path)

CPU times: user 11.4 s, sys: 1.51 s, total: 13 s
Wall time: 31.6 s

,bigAccountId,FundingMonth,LoanStatus,CreditorProgramInitial,strTier,intOpenBKType,Portfolio,DebtorState,ContractDate,BookingDate,...,mnyManheim,ManheimToNADA,RiskByFinanced,PTIbyAmtFinanced,DTIbyAmtFinanced,bitSystemApproval,SegmentedScorebyFinanced,bitEncore,DealerType,intVehicleClass
0,2455722,2016-02-01,C,P,B,NaN,N,WI,2016-02-23,2016-02-29,...,0.0,NaN,2553.269319,2561.394030,9073.705357,NaN,1.188365e+06,NaN,Independent,3
1,2456890,2016-02-01,T,P,A,7.0,N,AZ,2016-02-23,2016-02-26,...,NaN,NaN,1246.816422,2996.491635,7860.551800,True,1.801351e+06,NaN,Franchise,1
2,2458361,2016-03-01,T,P,B,13.0,N,TX,2016-02-26,2016-03-17,...,NaN,NaN,3097.847712,2250.858913,7600.133403,NaN,8.557692e+05,NaN,Franchise,3
3,2458742,2016-03-01,C,P,B,NaN,N,TN,2016-02-24,2016-03-02,...,1962.0,NaN,3459.038291,2891.211741,7998.883116,NaN,1.398991e+06,NaN,Franchise,1
4,2393432,2016-02-01,T,P,C,NaN,V,AZ,2016-01-27,2016-02-03,...,NaN,NaN,2467.768790,2111.901286,7158.521301,True,1.260482e+06,True,Franchise,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416840,3161264,2017-06-01,C,P,B,7.0,N,UT,2017-06-07,2017-06-08,...,0.0,NaN,940.944978,1206.220752,6811.066051,True,1.694374e+06,NaN,Franchise,2
416841,3166668,2017-06-01,T,P,B,NaN,X,CO,2017-05-27,2017-06-19,...,NaN,NaN,738.402244,1865.881468,9114.983672,NaN,1.727990e+06,NaN,Franchise,2
416842,1976283,2015-03-01,C,P,A1,13.0,N,CO,2015-02-28,2015-03-04,...,0.0,NaN,372.748892,1102.528770,10246.864139,NaN,2.621161e+06,NaN,Franchise,3
416843,1977239,2015-03-01,C,P,B,7.0,N,IL,2015-03-03,2015-03-09,...,2800.0,NaN,2500.100268,2324.032625,5322.306308,True,8.867449e+05,NaN,Franchise,2
416844,1986067,2015-03-01,T,P,A,7.0,N,UT,2015-03-09,2015-03-30,...,NaN,NaN,NaN,1279.096307,6694.329376,NaN,NaN,NaN,Franchise,3

### Tag franchise for example of applying function row-wise (one arg)

In [11]:
df['tag_franchise'] = df.apply(
    lambda x: tag_franchise(
        str_dealer_type=x['DealerType'],
    ),
    axis=1,
)
df

,bigAccountId,FundingMonth,LoanStatus,CreditorProgramInitial,strTier,intOpenBKType,Portfolio,DebtorState,ContractDate,BookingDate,...,ManheimToNADA,RiskByFinanced,PTIbyAmtFinanced,DTIbyAmtFinanced,bitSystemApproval,SegmentedScorebyFinanced,bitEncore,DealerType,intVehicleClass,tag_franchise
0,2455722,2016-02-01,C,P,B,NaN,N,WI,2016-02-23,2016-02-29,...,NaN,2553.269319,2561.394030,9073.705357,NaN,1.188365e+06,NaN,Independent,3,0
1,2456890,2016-02-01,T,P,A,7.0,N,AZ,2016-02-23,2016-02-26,...,NaN,1246.816422,2996.491635,7860.551800,True,1.801351e+06,NaN,Franchise,1,1
2,2458361,2016-03-01,T,P,B,13.0,N,TX,2016-02-26,2016-03-17,...,NaN,3097.847712,2250.858913,7600.133403,NaN,8.557692e+05,NaN,Franchise,3,1
3,2458742,2016-03-01,C,P,B,NaN,N,TN,2016-02-24,2016-03-02,...,NaN,3459.038291,2891.211741,7998.883116,NaN,1.398991e+06,NaN,Franchise,1,1
4,2393432,2016-02-01,T,P,C,NaN,V,AZ,2016-01-27,2016-02-03,...,NaN,2467.768790,2111.901286,7158.521301,True,1.260482e+06,True,Franchise,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416840,3161264,2017-06-01,C,P,B,7.0,N,UT,2017-06-07,2017-06-08,...,NaN,940.944978,1206.220752,6811.066051,True,1.694374e+06,NaN,Franchise,2,1
416841,3166668,2017-06-01,T,P,B,NaN,X,CO,2017-05-27,2017-06-19,...,NaN,738.402244,1865.881468,9114.983672,NaN,1.727990e+06,NaN,Franchise,2,1
416842,1976283,2015-03-01,C,P,A1,13.0,N,CO,2015-02-28,2015-03-04,...,NaN,372.748892,1102.528770,10246.864139,NaN,2.621161e+06,NaN,Franchise,3,1
416843,1977239,2015-03-01,C,P,B,7.0,N,IL,2015-03-03,2015-03-09,...,NaN,2500.100268,2324.032625,5322.306308,True,8.867449e+05,NaN,Franchise,2,1
416844,1986067,2015-03-01,T,P,A,7.0,N,UT,2015-03-09,2015-03-30,...,NaN,NaN,1279.096307,6694.329376,NaN,NaN,NaN,Franchise,3,1

### Tag independent for example of applying function row-wise (multiple args)

In [12]:
df['tag_independent'] = df.apply(
    lambda x: tag_dealer_type(
        str_dealer_type=x['DealerType'],
        str_target_dealer_type='Independent',
    ),
    axis=1,
)
df

,bigAccountId,FundingMonth,LoanStatus,CreditorProgramInitial,strTier,intOpenBKType,Portfolio,DebtorState,ContractDate,BookingDate,...,RiskByFinanced,PTIbyAmtFinanced,DTIbyAmtFinanced,bitSystemApproval,SegmentedScorebyFinanced,bitEncore,DealerType,intVehicleClass,tag_franchise,tag_independent
0,2455722,2016-02-01,C,P,B,NaN,N,WI,2016-02-23,2016-02-29,...,2553.269319,2561.394030,9073.705357,NaN,1.188365e+06,NaN,Independent,3,0,1
1,2456890,2016-02-01,T,P,A,7.0,N,AZ,2016-02-23,2016-02-26,...,1246.816422,2996.491635,7860.551800,True,1.801351e+06,NaN,Franchise,1,1,0
2,2458361,2016-03-01,T,P,B,13.0,N,TX,2016-02-26,2016-03-17,...,3097.847712,2250.858913,7600.133403,NaN,8.557692e+05,NaN,Franchise,3,1,0
3,2458742,2016-03-01,C,P,B,NaN,N,TN,2016-02-24,2016-03-02,...,3459.038291,2891.211741,7998.883116,NaN,1.398991e+06,NaN,Franchise,1,1,0
4,2393432,2016-02-01,T,P,C,NaN,V,AZ,2016-01-27,2016-02-03,...,2467.768790,2111.901286,7158.521301,True,1.260482e+06,True,Franchise,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416840,3161264,2017-06-01,C,P,B,7.0,N,UT,2017-06-07,2017-06-08,...,940.944978,1206.220752,6811.066051,True,1.694374e+06,NaN,Franchise,2,1,0
416841,3166668,2017-06-01,T,P,B,NaN,X,CO,2017-05-27,2017-06-19,...,738.402244,1865.881468,9114.983672,NaN,1.727990e+06,NaN,Franchise,2,1,0
416842,1976283,2015-03-01,C,P,A1,13.0,N,CO,2015-02-28,2015-03-04,...,372.748892,1102.528770,10246.864139,NaN,2.621161e+06,NaN,Franchise,3,1,0
416843,1977239,2015-03-01,C,P,B,7.0,N,IL,2015-03-03,2015-03-09,...,2500.100268,2324.032625,5322.306308,True,8.867449e+05,NaN,Franchise,2,1,0
416844,1986067,2015-03-01,T,P,A,7.0,N,UT,2015-03-09,2015-03-30,...,NaN,1279.096307,6694.329376,NaN,NaN,NaN,Franchise,3,1,0

### Make multiple tags in a dynamic list

In [13]:
# create a list of the unique values in column
list_str_dealer_type = list(df['DealerType'].value_counts().index)

# create a tag column for each unique value in column
for str_dealer_type in tqdm(list_str_dealer_type):
    df[f'tag_{str_dealer_type}'] = df.apply(
        lambda x: tag_dealer_type(
            str_dealer_type=x['DealerType'],
            str_target_dealer_type=str_dealer_type,
        ),
        axis=1,
    )
# show
df

100%|██████████| 4/4 [00:23<00:00,  6.00s/it]

,bigAccountId,FundingMonth,LoanStatus,CreditorProgramInitial,strTier,intOpenBKType,Portfolio,DebtorState,ContractDate,BookingDate,...,SegmentedScorebyFinanced,bitEncore,DealerType,intVehicleClass,tag_franchise,tag_independent,tag_Franchise,tag_Independent,tag_Referral,tag_Finance Express
0,2455722,2016-02-01,C,P,B,NaN,N,WI,2016-02-23,2016-02-29,...,1.188365e+06,NaN,Independent,3,0,1,0,1,0,0
1,2456890,2016-02-01,T,P,A,7.0,N,AZ,2016-02-23,2016-02-26,...,1.801351e+06,NaN,Franchise,1,1,0,1,0,0,0
2,2458361,2016-03-01,T,P,B,13.0,N,TX,2016-02-26,2016-03-17,...,8.557692e+05,NaN,Franchise,3,1,0,1,0,0,0
3,2458742,2016-03-01,C,P,B,NaN,N,TN,2016-02-24,2016-03-02,...,1.398991e+06,NaN,Franchise,1,1,0,1,0,0,0
4,2393432,2016-02-01,T,P,C,NaN,V,AZ,2016-01-27,2016-02-03,...,1.260482e+06,True,Franchise,3,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416840,3161264,2017-06-01,C,P,B,7.0,N,UT,2017-06-07,2017-06-08,...,1.694374e+06,NaN,Franchise,2,1,0,1,0,0,0
416841,3166668,2017-06-01,T,P,B,NaN,X,CO,2017-05-27,2017-06-19,...,1.727990e+06,NaN,Franchise,2,1,0,1,0,0,0
416842,1976283,2015-03-01,C,P,A1,13.0,N,CO,2015-02-28,2015-03-04,...,2.621161e+06,NaN,Franchise,3,1,0,1,0,0,0
416843,1977239,2015-03-01,C,P,B,7.0,N,IL,2015-03-03,2015-03-09,...,8.867449e+05,NaN,Franchise,2,1,0,1,0,0,0
416844,1986067,2015-03-01,T,P,A,7.0,N,UT,2015-03-09,2015-03-30,...,NaN,NaN,Franchise,3,1,0,1,0,0,0

### Iterate and create a df

In [14]:
# # get list of cols
# list_cols = list(df.columns)
# for a, col in enumerate(list_cols):
#     print(f'{a+1} - {col}')

In [27]:
# get random sample of rows
df_tmp = df.sample(frac=0.01, random_state=42)

# get cols
list_cols = list(df_tmp.columns)

# iterate and create df
list_dict_row = []
for col in tqdm(list_cols):
    try:
        # get mean
        flt_mean = df_tmp[col].mean()
        # get median
        flt_mdn = df_tmp[col].median()
        # create dict
        dict_row = {
            'col': col,
            'mean': flt_mean,
            'median': flt_mdn,
        }
        list_dict_row.append(dict_row)
    except TypeError:
        pass

# make df
df_tmp = pd.DataFrame(list_dict_row)
# show
df_tmp

100%|██████████| 212/212 [00:00<00:00, 1754.02it/s]

                          col          mean       median
0                bigAccountId  2.578510e+06  1905580.500
1               intOpenBKType  8.366128e+00        7.000
2                 AmtFinanced  1.827011e+04    17820.805
3        OriginalInterestRate  1.942555e+01       19.490
4    AmtFinancedbyOriginalAPR  3.638461e+05   348400.800
..                        ...           ...          ...
173           tag_independent  2.060940e-01        0.000
174             tag_Franchise  7.607965e-01        1.000
175           tag_Independent  2.060940e-01        0.000
176              tag_Referral  2.399232e-03        0.000
177       tag_Finance Express  0.000000e+00        0.000

[178 rows x 3 columns]

### Frequency tables

In [ ]:
# initialize class
cls_plot_proportions = PlotProportions()
# create proportion table by calling method
cls_plot_proportions.create_proportion_table(df=df)
# plot proportions by calling method
str_filename = 'plt_dealer_type_prop.png'
str_local_path = f'{str_dirname_output}/{str_filename}'
cls_plot_proportions.plot_proportions(
    str_local_path=str_local_path,
    bool_show_plot=True,
)
# show table
cls_plot_proportions.df_freq

### Pickle class

In [ ]:
str_filename = 'cls_plot_proportions.pkl'
str_local_path = f'{str_dirname_output}/{str_filename}'
pickle.dump(cls_plot_proportions, open(str_local_path, 'wb'))

### Read a pickled object

In [ ]:
cls_plot_proportions = pickle.load(open(str_local_path, 'rb'))
cls_plot_proportions

### Show attributes

In [ ]:
# table
cls_plot_proportions.df_freq

In [ ]:
# plot
cls_plot_proportions.fig

### Write a csv file to local output

In [ ]:
str_filename = 'df_freq.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
cls_plot_proportions.df_freq.to_csv(
    str_local_path,
    index=False,
)

### Write a csv to s3

In [ ]:
str_filename = 'df_freq.csv'
str_uri = f's3://{str_project}/{str_task}/{str_subtask}/{str_filename}'
cls_plot_proportions.df_freq.to_csv(
    str_uri,
    index=False,
)

### Read the gzip file

In [ ]:
%%time

str_filename = 'df_originations_since_jan.gzip'
str_local_path = f'../../02_sql/output/{str_filename}'
str_uri = f's3://{str_project}/02_sql/output/{str_filename}'
df_tmp = pd.read_parquet(
    #str_local_path,
    str_uri,
)
df_tmp

### Left Outer Join (Left Join)

In [ ]:
df_left_outer = pd.merge(
    left=df,
    right=df_tmp,
    on='bigAccountId',
    how='left',
)
df_left_outer

### Inner Left Join

In [ ]:
df_inner_left = pd.merge(
    left=df,
    right=df_tmp,
    on='bigAccountId',
    how='inner',
)
df_inner_left

### Groupby F

In [ ]:
df['RiskByFinanced_sum'] = df['RiskByFinanced']
df['RiskByFinanced_mean'] = df['RiskByFinanced']
df['count'] = 1
df_tmp = df.groupby(['DebtorState', 'intVehicleClass'], as_index=False).agg({
    'RiskByFinanced_sum': 'sum',
    'RiskByFinanced_mean': 'mean',
    'PTIbyAmtFinanced': 'sum',
    'Portfolio': 'first',
    'count': 'sum',
})
df_tmp

In [ ]:
df

In [ ]:
gk = df.groupby(['DebtorState', 'intVehicleClass']).SegmentedScorebyFinanced.agg(["mean"])
gk.columns = ['Mean SegmentedScorebyFinanced']
gk

### Exercises 05-14-2024 DNRR

In [ ]:
list(df_tmp.columns)

In [ ]:
list(df.columns)

In [ ]:
list_cols = ['bigAccountId', 'week_of_month', 'GEN11_ECNL', 'GEN12_ECNL', 'DL_ECNL']
list_cols

In [ ]:
df_tmp[list_cols]

In [ ]:
list_cols_OSJ = ['bigAccountId', 'GEN11_ECNL', 'GEN12_ECNL', 'DL_ECNL']
list_cols_OSJ

In [ ]:
list_cols_AFA = ['Portfolio', 'DealerName', 'VehicleMake']
list_cols_AFA

In [ ]:
OSJ = df_tmp[list_cols_OSJ]
AFA = df[list_cols_AFA]
OSJ_2 = OSJ.join(AFA)
print(OSJ_2)