In [1]:
import os
import pandas as pd
import datetime as dt

In [2]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')

str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

str_subtask = os.getcwd().split('/')[6]
print(f'Subtask: {str_subtask}')

Project: 20231010-gen-xii
Task: ad_hoc
Subtask: 09_policy_simulation

In [3]:
str_uri = 's3://20231010-gen-xii/ad_hoc/09_policy_simulation/df.gzip'
df = pd.read_parquet(str_uri)
df

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,lgd_gen12,pd_gen13,lgd_gen13,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy
0,5782431,10/02/2021 11:48:53,2024-12-19 18:09:20-07:00,0.0,1.270000,1.0,1.0,0.145092,1.0,0.0,...,0.607378,0.541495,0.390043,0,0.669610,0,0.498446,0,1.000000,0
1,7861802,05/14/2024 16:50:49,2024-12-04 18:28:18-07:00,0.0,1.074516,0.0,31.0,0.019426,1.0,0.0,...,0.649240,0.585708,0.337281,1,0.887952,0,0.466214,0,1.000000,0
2,7986128,07/08/2024 15:08:45,2024-12-27 21:55:29-07:00,1.0,1.061934,-4.0,16.0,NaN,0.0,0.0,...,0.693575,0.627577,0.259641,0,0.302763,1,0.384549,0,0.302763,1
3,8033187,07/28/2024 08:10:03,2025-01-03 23:04:31-07:00,1.0,1.231172,0.0,12.0,0.100000,0.0,0.0,...,0.630260,0.346536,0.293804,0,0.122551,1,0.240280,1,0.122551,1
4,8155274,08/28/2024 12:59:43,2024-12-23 21:20:25-07:00,1.0,1.261982,0.0,12.0,0.646154,0.0,0.0,...,0.653972,0.397763,0.316725,0,0.194410,1,0.297317,1,0.194410,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143750,8690092,02/26/2025 16:58:37,2025-02-26 23:58:56-07:00,0.0,1.080757,0.0,6.0,NaN,0.0,0.0,...,0.673393,0.646136,0.337281,0,0.643184,0,0.514314,0,0.643184,0
143751,8690094,02/26/2025 16:58:59,2025-02-26 23:59:15-07:00,0.0,0.990438,1.0,10.0,0.057895,1.0,0.0,...,0.598153,0.524182,0.277756,1,0.181296,1,0.343604,1,1.000000,0
143752,8690095,02/26/2025 16:59:04,2025-02-26 23:59:48-07:00,0.0,0.532826,0.0,2.0,NaN,0.0,1.0,...,0.639697,0.127924,0.199397,0,0.142067,1,0.060198,1,0.040000,1
143753,8690096,02/26/2025 16:59:04,2025-02-26 23:59:17-07:00,0.0,1.270000,999.0,999.0,NaN,1.0,0.0,...,0.658927,0.789041,0.390043,0,0.219937,1,0.726313,0,1.000000,0
143754,8690098,02/26/2025 16:59:09,2025-02-26 23:59:35-07:00,0.0,1.589148,0.0,14.0,NaN,0.0,0.0,...,0.664557,0.457562,0.416881,1,0.105802,1,0.450167,0,0.105802,1

#### Rm accounts with app date before 02-26-2025

In [4]:
str_dtm_effective_date = '2/26/2025 00:00:00'
dtm_effective_date = dt.datetime.strptime(str_dtm_effective_date, '%m/%d/%Y %H:%M:%S')

df['applicationdate__app'] = pd.to_datetime(df['applicationdate__app'])
df = df[df['applicationdate__app'] >= dtm_effective_date].copy()
df

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,lgd_gen12,pd_gen13,lgd_gen13,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy
141232,8685914,2025-02-26 05:29:02,2025-02-26 12:29:18-07:00,0.0,1.162727,0.0,18.0,NaN,0.0,0.0,...,0.624829,0.630603,0.350185,1,0.710492,0,0.521153,0,0.710492,0
141233,8685915,2025-02-26 05:32:49,2025-02-26 20:40:12-07:00,1.0,1.110685,0.0,19.0,0.139601,0.0,0.0,...,0.682040,0.294014,0.259641,1,0.181090,1,0.180158,1,0.181090,1
141234,8685926,2025-02-26 06:27:37,2025-02-26 13:27:52-07:00,0.0,1.286566,1.0,3.0,0.130000,1.0,0.0,...,0.641956,0.493614,0.390043,1,0.419817,0,0.454372,0,1.000000,0
141235,8685927,2025-02-26 06:28:15,2025-02-26 13:28:31-07:00,0.0,1.139315,0.0,8.0,0.001695,1.0,0.0,...,0.626105,0.597005,0.337281,1,0.431602,0,0.475206,0,1.000000,0
141236,8685930,2025-02-26 06:31:02,2025-02-26 13:31:20-07:00,0.0,1.051688,0.0,18.0,NaN,0.0,0.0,...,0.706801,0.449122,0.337281,0,0.304307,1,0.357494,0,0.304307,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143750,8690092,2025-02-26 16:58:37,2025-02-26 23:58:56-07:00,0.0,1.080757,0.0,6.0,NaN,0.0,0.0,...,0.673393,0.646136,0.337281,0,0.643184,0,0.514314,0,0.643184,0
143751,8690094,2025-02-26 16:58:59,2025-02-26 23:59:15-07:00,0.0,0.990438,1.0,10.0,0.057895,1.0,0.0,...,0.598153,0.524182,0.277756,1,0.181296,1,0.343604,1,1.000000,0
143752,8690095,2025-02-26 16:59:04,2025-02-26 23:59:48-07:00,0.0,0.532826,0.0,2.0,NaN,0.0,1.0,...,0.639697,0.127924,0.199397,0,0.142067,1,0.060198,1,0.040000,1
143753,8690096,2025-02-26 16:59:04,2025-02-26 23:59:17-07:00,0.0,1.270000,999.0,999.0,NaN,1.0,0.0,...,0.658927,0.789041,0.390043,0,0.219937,1,0.726313,0,1.000000,0
143754,8690098,2025-02-26 16:59:09,2025-02-26 23:59:35-07:00,0.0,1.589148,0.0,14.0,NaN,0.0,0.0,...,0.664557,0.457562,0.416881,1,0.105802,1,0.450167,0,0.105802,1

#### Check rule 1 - rp01s

In [5]:
df['tag_rp01s'] = df['rp01s__tu'].apply(
    lambda x: 1 if x > 1 else 0,
)

In [6]:
df_tmp = df[df['tag_rp01s'] == 1].copy()
df_tmp

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,pd_gen13,lgd_gen13,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy,tag_rp01s
141241,8685942,2025-02-26 06:53:44,2025-02-26 13:53:55-07:00,0.0,1.199010,999.0,999.0,NaN,1.0,0.0,...,0.918283,0.350185,0,0.472948,0,0.758902,0,1.0,0,1
141246,8685955,2025-02-26 07:05:47,2025-02-26 14:05:57-07:00,0.0,1.306774,999.0,999.0,NaN,1.0,0.0,...,0.840166,0.390043,0,0.299069,1,0.773374,0,1.0,0,1
141266,8685992,2025-02-26 07:29:33,2025-02-26 14:29:46-07:00,0.0,1.103300,999.0,999.0,NaN,1.0,0.0,...,0.782676,0.337281,0,0.344675,1,0.622997,0,1.0,0,1
141267,8685994,2025-02-26 07:33:06,2025-02-26 14:33:27-07:00,0.0,1.114740,2.0,27.0,0.002885,1.0,0.0,...,0.540499,0.337281,1,0.784235,0,0.430228,0,1.0,0,1
141283,8686030,2025-02-26 07:43:21,2025-02-26 14:43:37-07:00,0.0,1.071484,2.0,7.0,0.043741,1.0,0.0,...,0.642773,0.337281,0,0.450804,0,0.511637,0,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143699,8690015,2025-02-26 16:45:51,2025-02-26 23:46:25-07:00,0.0,1.407540,2.0,13.0,0.793720,1.0,0.0,...,0.624026,0.390043,0,0.390041,0,0.574416,0,1.0,0,1
143702,8690018,2025-02-26 16:46:10,2025-02-26 23:46:40-07:00,0.0,0.962744,999.0,999.0,1.000000,1.0,0.0,...,0.632674,0.277756,0,0.601613,0,0.414721,0,1.0,0,1
143719,8690046,2025-02-26 16:51:42,2025-02-26 23:52:00-07:00,0.0,1.169921,2.0,41.0,1.000000,1.0,0.0,...,0.739853,0.350185,1,0.865437,0,0.611441,0,1.0,0,1
143736,8690069,2025-02-26 16:55:00,2025-02-26 23:55:26-07:00,0.0,0.836055,2.0,28.0,0.087189,1.0,0.0,...,0.626191,0.277756,1,0.275277,1,0.410471,0,1.0,0,1
143753,8690096,2025-02-26 16:59:04,2025-02-26 23:59:17-07:00,0.0,1.270000,999.0,999.0,NaN,1.0,0.0,...,0.789041,0.390043,0,0.219937,1,0.726313,0,1.0,0,1

#### Check rule 2 - g232s

In [7]:
df['tag_g232s'] = df['g232s__tu'].apply(
    lambda x: 1 if x > 1 else 0,
)

In [8]:
df_tmp = df[df['tag_g232s'] == 1].copy()
df_tmp

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,lgd_gen13,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy,tag_rp01s,tag_g232s
141232,8685914,2025-02-26 05:29:02,2025-02-26 12:29:18-07:00,0.0,1.162727,0.0,18.0,NaN,0.0,0.0,...,0.350185,1,0.710492,0,0.521153,0,0.710492,0,0,1
141233,8685915,2025-02-26 05:32:49,2025-02-26 20:40:12-07:00,1.0,1.110685,0.0,19.0,0.139601,0.0,0.0,...,0.259641,1,0.181090,1,0.180158,1,0.181090,1,0,1
141234,8685926,2025-02-26 06:27:37,2025-02-26 13:27:52-07:00,0.0,1.286566,1.0,3.0,0.130000,1.0,0.0,...,0.390043,1,0.419817,0,0.454372,0,1.000000,0,0,1
141235,8685927,2025-02-26 06:28:15,2025-02-26 13:28:31-07:00,0.0,1.139315,0.0,8.0,0.001695,1.0,0.0,...,0.337281,1,0.431602,0,0.475206,0,1.000000,0,0,1
141236,8685930,2025-02-26 06:31:02,2025-02-26 13:31:20-07:00,0.0,1.051688,0.0,18.0,NaN,0.0,0.0,...,0.337281,0,0.304307,1,0.357494,0,0.304307,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143750,8690092,2025-02-26 16:58:37,2025-02-26 23:58:56-07:00,0.0,1.080757,0.0,6.0,NaN,0.0,0.0,...,0.337281,0,0.643184,0,0.514314,0,0.643184,0,0,1
143751,8690094,2025-02-26 16:58:59,2025-02-26 23:59:15-07:00,0.0,0.990438,1.0,10.0,0.057895,1.0,0.0,...,0.277756,1,0.181296,1,0.343604,1,1.000000,0,0,1
143752,8690095,2025-02-26 16:59:04,2025-02-26 23:59:48-07:00,0.0,0.532826,0.0,2.0,NaN,0.0,1.0,...,0.199397,0,0.142067,1,0.060198,1,0.040000,1,0,1
143753,8690096,2025-02-26 16:59:04,2025-02-26 23:59:17-07:00,0.0,1.270000,999.0,999.0,NaN,1.0,0.0,...,0.390043,0,0.219937,1,0.726313,0,1.000000,0,1,1
143754,8690098,2025-02-26 16:59:09,2025-02-26 23:59:35-07:00,0.0,1.589148,0.0,14.0,NaN,0.0,0.0,...,0.416881,1,0.105802,1,0.450167,0,0.105802,1,0,1

#### Check rule 3 - pmt hx

In [9]:
df['tag_no_auto'] = df['ENG-wtd_avg'].apply(
    lambda x: 1 if pd.isnull(x) else 0,
)

In [10]:
df_tmp = df[df['tag_no_auto'] == 1].copy()
df_tmp

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy,tag_rp01s,tag_g232s,tag_no_auto
141232,8685914,2025-02-26 05:29:02,2025-02-26 12:29:18-07:00,0.0,1.162727,0.0,18.0,NaN,0.0,0.0,...,1,0.710492,0,0.521153,0,0.710492,0,0,1,1
141236,8685930,2025-02-26 06:31:02,2025-02-26 13:31:20-07:00,0.0,1.051688,0.0,18.0,NaN,0.0,0.0,...,0,0.304307,1,0.357494,0,0.304307,1,0,1,1
141241,8685942,2025-02-26 06:53:44,2025-02-26 13:53:55-07:00,0.0,1.199010,999.0,999.0,NaN,1.0,0.0,...,0,0.472948,0,0.758902,0,1.000000,0,1,1,1
141242,8685946,2025-02-26 06:57:47,2025-02-26 13:58:02-07:00,0.0,1.062193,-4.0,5.0,NaN,0.0,0.0,...,0,0.495443,0,0.461596,0,0.495443,0,0,1,1
141243,8685947,2025-02-26 06:59:54,2025-02-26 14:00:16-07:00,0.0,1.383365,-4.0,2.0,NaN,0.0,0.0,...,0,0.767391,0,0.785176,0,0.767391,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143749,8690089,2025-02-26 16:57:56,2025-02-26 23:58:16-07:00,0.0,1.103075,0.0,6.0,NaN,0.0,0.0,...,0,0.510831,0,0.448229,0,0.510831,0,0,1,1
143750,8690092,2025-02-26 16:58:37,2025-02-26 23:58:56-07:00,0.0,1.080757,0.0,6.0,NaN,0.0,0.0,...,0,0.643184,0,0.514314,0,0.643184,0,0,1,1
143752,8690095,2025-02-26 16:59:04,2025-02-26 23:59:48-07:00,0.0,0.532826,0.0,2.0,NaN,0.0,1.0,...,0,0.142067,1,0.060198,1,0.040000,1,0,1,1
143753,8690096,2025-02-26 16:59:04,2025-02-26 23:59:17-07:00,0.0,1.270000,999.0,999.0,NaN,1.0,0.0,...,0,0.219937,1,0.726313,0,1.000000,0,1,1,1
143754,8690098,2025-02-26 16:59:09,2025-02-26 23:59:35-07:00,0.0,1.589148,0.0,14.0,NaN,0.0,0.0,...,1,0.105802,1,0.450167,0,0.105802,1,0,1,1

In [11]:
df_tmp = df[df['tag_no_auto'] == 0].copy()
df_tmp

,accountid,applicationdate__app,request_datetime,ENG-bk,ENG-loan_to_value,rp01s__tu,g232s__tu,ENG-wtd_avg,tag_policy_decline,tag_policy_approval,...,has_inst_tag,ecnl_gen12,tag_approved_gen12,ecnl_gen13,tag_approved_gen13,ecnl_policy,tag_approved_policy,tag_rp01s,tag_g232s,tag_no_auto
141233,8685915,2025-02-26 05:32:49,2025-02-26 20:40:12-07:00,1.0,1.110685,0.0,19.0,0.139601,0.0,0.0,...,1,0.181090,1,0.180158,1,0.181090,1,0,1,0
141234,8685926,2025-02-26 06:27:37,2025-02-26 13:27:52-07:00,0.0,1.286566,1.0,3.0,0.130000,1.0,0.0,...,1,0.419817,0,0.454372,0,1.000000,0,0,1,0
141235,8685927,2025-02-26 06:28:15,2025-02-26 13:28:31-07:00,0.0,1.139315,0.0,8.0,0.001695,1.0,0.0,...,1,0.431602,0,0.475206,0,1.000000,0,0,1,0
141237,8685931,2025-02-26 06:32:03,2025-02-26 13:32:28-07:00,0.0,1.226207,1.0,16.0,0.594253,0.0,0.0,...,1,0.460517,0,0.567246,0,0.460517,0,0,1,0
141238,8685935,2025-02-26 06:41:14,2025-02-26 15:23:48-07:00,0.0,1.286933,0.0,21.0,1.000000,0.0,0.0,...,0,0.039134,1,0.494204,0,0.039134,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143743,8690082,2025-02-26 16:57:12,2025-02-26 23:57:29-07:00,0.0,0.998733,1.0,12.0,0.333333,1.0,0.0,...,0,0.263038,1,0.378675,0,1.000000,0,0,1,0
143744,8690083,2025-02-26 16:57:22,2025-02-26 23:57:38-07:00,0.0,1.251641,0.0,8.0,0.873118,0.0,0.0,...,1,0.455667,0,0.397934,0,0.455667,0,0,1,0
143747,8690087,2025-02-26 16:57:37,2025-02-26 23:57:55-07:00,0.0,0.866735,1.0,9.0,0.181750,1.0,0.0,...,1,0.333677,1,0.248732,1,1.000000,0,0,1,0
143748,8690088,2025-02-26 16:57:44,2025-02-26 23:58:08-07:00,0.0,0.995315,0.0,18.0,0.905920,0.0,0.0,...,1,0.733259,0,0.346887,1,0.733259,0,0,1,0
143751,8690094,2025-02-26 16:58:59,2025-02-26 23:59:15-07:00,0.0,0.990438,1.0,10.0,0.057895,1.0,0.0,...,1,0.181296,1,0.343604,1,1.000000,0,0,1,0

#### Write to s3

In [12]:
%%time

str_filename = 'df_w_tags.gzip'
str_uri = f's3://{str_project}/{str_task}/{str_subtask}/{str_filename}'
df.to_parquet(
    str_uri,
    compression='gzip',
)

CPU times: user 31.5 ms, sys: 10.4 ms, total: 41.9 ms
Wall time: 273 ms