In [1]:
import os
import pandas as pd
import numpy as np

### Functions

### Constants

In [2]:
str_dirname_output = './output'

### Output directory

In [3]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Get training means

In [4]:
str_filename = 'df_mean.csv'
str_local_path = f'../03_training_data_frequency/output/{str_filename}'
df = pd.read_csv(str_local_path)
# rename
dict_rename = {
    'mean': 'mean_train',
}
df.rename(columns=dict_rename, inplace=True)
df

                                flag  mean_train
0   Early_Pay_Delinquency_15_60_Flag    0.033302
1   Early_Pay_Delinquency_30_90_Flag    0.027206
2  Early_Pay_Delinquency_30_180_Flag    0.083309
3  Early_Pay_Delinquency_30_360_Flag    0.178980

### Get test means

In [5]:
str_filename = 'df_mean.csv'
str_local_path = f'../02_test_data_frequency/output/{str_filename}'
df_tmp = pd.read_csv(str_local_path)
# rename
dict_rename = {
    'mean': 'mean_test',
}
df_tmp.rename(columns=dict_rename, inplace=True)
df_tmp

                                flag  mean_test
0   Early_Pay_Delinquency_15_60_Flag   0.141308
1   Early_Pay_Delinquency_30_90_Flag   0.127363
2  Early_Pay_Delinquency_30_180_Flag   0.305237
3  Early_Pay_Delinquency_30_360_Flag   0.522467

### Join

In [6]:
df = pd.merge(
    left=df,
    right=df_tmp,
    on='flag',
    how='left',
)
df

                                flag  mean_train  mean_test
0   Early_Pay_Delinquency_15_60_Flag    0.033302   0.141308
1   Early_Pay_Delinquency_30_90_Flag    0.027206   0.127363
2  Early_Pay_Delinquency_30_180_Flag    0.083309   0.305237
3  Early_Pay_Delinquency_30_360_Flag    0.178980   0.522467

### Save

In [7]:
str_filename = 'df_mean.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)